---
title: "Figure 3. LBD vs AD"
author: "Kimberly Olney"
date: "07/10/2023"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
library("readxl")
#source(here::here("scripts/R", "gtf_path.R"))
condition <- c("TYPE")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))
```
# Binary list shared gene function
```{r}
fromList <- function (input) {
  # Same as original fromList()...
  elements <- unique(unlist(input))
  data <- unlist(lapply(input, function(x) {
      x <- as.vector(match(elements, x))
      }))
  data[is.na(data)] <- as.integer(0)
  data[data != 0] <- as.integer(1)
  data <- data.frame(matrix(data, ncol = length(input), byrow = F))
  data <- data[which(rowSums(data) != 0), ]
  names(data) <- names(input)
  # ... Except now it conserves your original value names!
  row.names(data) <- elements
  return(data)
  }
```

```{r}
allComparisons <- c("LBDvsControl", 
                    "LBDvsAD", 
                    "ADvsControl")
allComparisons # check

for (i in allComparisons) {
  filepath <- paste0(
    "../../../results/",
    tool,
    "/DEGs/", condition, "_", 
    i,
    "_gene_DEGs_FDRq1.00.txt"
  )
  assign(paste0(i),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
  # increment
}
```
```{r}
# DEGs by FDRq <= 0.05 & log2FC 
LBDvsControl_up <- subset(LBDvsControl, logFC > 0.25 & adj.P.Val <= 0.05)
LBDvsControl_down <- subset(LBDvsControl, logFC < -0.25 & adj.P.Val <= 0.05)
ADvsControl_up <- subset(ADvsControl, logFC > 0.25 & adj.P.Val <= 0.05)
ADvsControl_down <- subset(ADvsControl, logFC < -0.25 & adj.P.Val <= 0.05)
```
# Upset
```{r}
list_input <- list("LBD down-regulated" = LBDvsControl_down$gene_name,
                   "LBD up-regulated" = LBDvsControl_up$gene_name,
                   "AD down-regulated" = ADvsControl_down$gene_name,
                   "AD up-regulated" = ADvsControl_up$gene_name)
data <- fromList(list_input)

upset_gene <- upset(data, name='', set_sizes = FALSE,
      c('LBD down-regulated',
        'AD down-regulated',
        'LBD up-regulated',
        'AD up-regulated'),
      themes=upset_modify_themes(
        list('intersections_matrix'=theme(text=element_text(size=10),
              plot.margin = margin(0, 0, 0, 0, "cm")),
          'overall_sizes' = theme(axis.text.x = element_text(size =10), 
              plot.margin = margin(0, 0, 0, 0, "cm")))),
  queries=list(
    upset_query(set='LBD down-regulated', fill='blue'),
    upset_query(set='AD down-regulated', fill='blue'),
    upset_query(set='LBD up-regulated', fill='red'),
    upset_query(set='AD up-regulated', fill='red')
  ),
  intersections = list(c('LBD down-regulated', 'AD down-regulated'), 
                       'LBD down-regulated',
                       'AD down-regulated', 
                       c('LBD up-regulated', 'AD up-regulated'), 
                       'LBD up-regulated',
                       'AD up-regulated', 
                       c('LBD up-regulated', 'AD down-regulated')

  ),
  base_annotations=list(
    'Intersection size'=(
        intersection_size(
        size=2,
        text = list(size = 2.5),
        text_mapping = aes(),
        bar_number_threshold=3,  # show all numbers on top of bars
        width=0.3,   # reduce width of the bars
        mapping=aes(fill='bars_color')
      )
      + scale_fill_manual(values=c('grey'), guide='none')
      + scale_y_continuous(expand=expansion(mult=c(0, 0.5)))
      + theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.margin = margin(0, 0, 0, 0, "cm"), 
          axis.line=element_line(colour='black')))),
  matrix=intersection_matrix(
      geom=geom_point(
        shape='circle filled',
        size=2,
        stroke=0.45)) +
        theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8),
              axis.text.x = element_blank(),
              axis.title.x = element_blank(), 
              plot.margin = margin(0, 0, 0, 0, "cm")),
    sort_sets=FALSE,
  sort_intersections=FALSE)
upset_gene
```

# LBD & AD - metascape shared 
### Metascape Enrichment shared between LBD & AD
```{r}
# read in enrichment analysis results
shared_up_enrich_results <-
  read.csv("../../../results/star/metascape/Disease_vs_Control_up_regulated/Enrichment_heatmap/HeatmapSelectedGO.csv")
shared_up_enrich_results$Description <-
      gsub(
       "regulation of tumor necrosis factor superfamily cytokine production",
        "reg tumor necrosis factor cytokine production",
        shared_up_enrich_results$Description
      )
shared_up_enrich_results$Description <- factor(shared_up_enrich_results$Description, levels = shared_up_enrich_results$Description)
shared_up_enrich_results <- melt(shared_up_enrich_results)
shared_up_enrich_results$variable <-
      gsub(
       "X_LogP_ADvsControl",
        "AD",
        shared_up_enrich_results$variable
      )
shared_up_enrich_results$variable <-
      gsub(
       "X_LogP_LBDvsControl",
        "LBD",
        shared_up_enrich_results$variable
      )
# plot - up
shared_up_enric_heatmap <- 
  ggplot(shared_up_enrich_results, aes(variable, fct_rev(Description), fill= value)) + 
  geom_tile() +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "", y = "") +
  guides(fill = guide_legend(
    size = 1,
    title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)")
  )) +
  scale_fill_gradientn(
    colours = c("#800026FF","#FD8D3CFF", "#FFFFCCFF"),
    guide = "legend",
    limits = c(-22,-3),
  ) +  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 2.25)) +
    ggtitle("Up-regulated enrichment summaries")

addSmallLegend <- function(shared_up_enric_heatmap, pointSize = 3, textSize = 6, spaceLegend = .5) {
    shared_up_enric_heatmap +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.position = "right",
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
# Apply on original plot
shared_up_enric_heatmap <- addSmallLegend(shared_up_enric_heatmap)
shared_up_enric_heatmap
```

```{r down_heat}
#--------
# down
shared_down_enrich_results <-
  read.csv("../../../results/star/metascape/Disease_vs_Control_down_regulated/Enrichment_heatmap/HeatmapSelectedGO.csv")
shared_down_enrich_results$Description <- factor(shared_down_enrich_results$Description, levels = shared_down_enrich_results$Description)
shared_down_enrich_results <- melt(shared_down_enrich_results)
shared_down_enrich_results$variable <-
      gsub(
       "X_LogP_ADvsControl",
        "AD",
        shared_down_enrich_results$variable
      )
shared_down_enrich_results$variable <-
      gsub(
       "X_LogP_LBDvsControl",
        "LBD",
        shared_down_enrich_results$variable
      )
# plot - down
shared_down_enric_heatmap <- 
  ggplot(shared_down_enrich_results, aes(variable, fct_rev(Description), fill= value)) + 
  geom_tile() +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "", y = "") +
  guides(fill = guide_legend(
    size = 1,
    title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)")
  )) +
  scale_fill_gradientn(
    colours = c("#800026FF","#FD8D3CFF", "#FFFFCCFF"),
    guide = "legend",
    limits = c(-19,-2),
    breaks = c(-19, -15, -10, -5)
  ) +  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.1, 0.2, 0.1, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 1.95)) +
    ggtitle("Down-regulated enrichment summaries")

addSmallLegend <- function(shared_down_enric_heatmap, pointSize = 3, textSize = 6, spaceLegend = .5) {
    shared_down_enric_heatmap +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.position = "right",
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
# Apply on original plot
shared_down_enric_heatmap <- addSmallLegend(shared_down_enric_heatmap)
shared_down_enric_heatmap
```

# Correlation - significant genes
```{r}
ADandLBD <-
  merge(ADvsControl,
        LBDvsControl,
        by = "gene_name",
        all = T)
ADandLBD <- ADandLBD[c(1,2,6,7,8:15,22:29)]
colnames(ADandLBD) = c("gene_name", "chr", "gene_id","gene_type", "AD_logFC", "AD_CI.L", "AD_CI.R", "AD_AveExpr", "AD_t","AD_P.val", "AD_adj.P.Val", "AD_B", "LBD_logFC", "LBD_CI.L", "LBD_CI.R", "LBD_AveExpr", "LBD_t","LBD_P.val", "LBD_adj.P.Val", "LBD_B")

# significant in either 
ADandLBD <- subset(ADandLBD, (AD_logFC < -.25 & AD_adj.P.Val < 0.05) | (AD_logFC > 0.25 & AD_adj.P.Val < 0.05) |
                     (LBD_logFC < -.25 & LBD_adj.P.Val < 0.05) | (LBD_logFC > 0.25 & LBD_adj.P.Val < 0.05) )
ADandLBD_goi <- subset(ADandLBD, 
                        (AD_logFC < -0.5 & LBD_logFC < -0.5) | # down in both
                          (AD_logFC > .5 & LBD_logFC > 0.5) | # up in both
                          (AD_logFC > .5 & LBD_logFC < 0) | # up in AD, down in LBD
                          (AD_logFC < -.5 & LBD_logFC > 0)) # up in LBD, down in AD
ROS1_goi <- subset(ADandLBD, gene_name == "ROS1")
more_goi <- subset(ADandLBD, (AD_logFC > .15 & LBD_logFC < 0) | (AD_logFC < -.15 & LBD_logFC > 0.15)) 
more_goi <- more_goi[!(more_goi$gene_name %in% ADandLBD_goi$gene_name),]

sig_AD <- subset(ADandLBD, AD_adj.P.Val < 0.05 & LBD_adj.P.Val > 0.05)
sig_LBD <- subset(ADandLBD, LBD_adj.P.Val < 0.05 &  AD_adj.P.Val > 0.05)
sig_both <- subset(ADandLBD, AD_adj.P.Val < 0.05 & LBD_adj.P.Val < 0.05)

ADandLBD_corr_plot_sig <- ggplot(data = ADandLBD, 
  aes(x = AD_logFC, y = LBD_logFC, text = paste(gene_name))) +
  annotate(
    "rect",
    xmin = 0,
    xmax = 1.75,
    ymin = 1.75,
    ymax = 0,
    fill = "lightpink3",
    alpha = .1
  ) +  annotate(
    "rect",
    xmin = 0,
    xmax = -1.75,
    ymin = 0,
    ymax = -1.75,
    fill = "cadetblue3",
    alpha = .1) +
 # geom_abline(color = "gray40") +
  geom_abline(color = "gray80", linetype = 2) +
  geom_point(data = sig_AD, color=AD_color, shape=AD_shape) + 
  geom_point(data = sig_LBD, color=LBD_color, shape=LBD_shape) + 
  geom_point(data = sig_both, color="black", shape=25) + 
  geom_text_repel(
    data = sig_both, 
    aes(
    x = AD_logFC, 
    y = LBD_logFC,
    label = gene_name
    ),
    color = "black",
    fontface = "italic",
    size = 2, 
    max.overlaps = getOption("ggrepel.max.overlaps", default = 15)
    ) +
  geom_text_repel(
    data = sig_LBD, 
    aes(
    x = AD_logFC, 
    y = LBD_logFC,
    label = gene_name
    ),
    color = LBD_color,
    fontface = "italic",
    size = 2, 
    max.overlaps = getOption("ggrepel.max.overlaps", default = 30)
    ) +
    geom_text_repel(
    data = sig_AD, 
    aes(
    x = AD_logFC, 
    y = LBD_logFC,
    label = gene_name
    ),
    color = AD_color,
    fontface = "italic",
    size = 2, 
    max.overlaps = getOption("ggrepel.max.overlaps", default = 30)
    ) +
  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.4, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 0)) +
  labs(
    title = "Differentially expressed genes, FDRq < 0.05 & absolute log2FC > 0.25
Shared and unique between LBD and AD",
    x = expression(paste("  ", log[2](AD/Control))),
    y = expression(paste("  ", log[2](LBD/Control))))+
  scale_y_continuous(breaks = seq(-1.5, 1.5, by = .5), 
                     limits = c(-1.75, 1.75), expand = c(0,0)) +
  scale_x_continuous(breaks = seq(-1.5, 1.5, by = .5), 
                     limits = c(-1.75, 1.75), expand = c(0,0))
ADandLBD_corr_plot_sig
```
# Correlation - all genes 
```{r}
ADandLBD <-
  merge(ADvsControl,
        LBDvsControl,
        by = "gene_name",
        all = T)
ADandLBD <- ADandLBD[c(1,2,6,7,8:15,22:29)]
colnames(ADandLBD) = c("gene_name", "chr", "gene_id","gene_type", "AD_logFC", "AD_CI.L", "AD_CI.R", "AD_AveExpr", "AD_t","AD_P.val", "AD_adj.P.Val", "AD_B", "LBD_logFC", "LBD_CI.L", "LBD_CI.R", "LBD_AveExpr", "LBD_t","LBD_P.val", "LBD_adj.P.Val", "LBD_B")

ADandLBD_goi <- subset(ADandLBD, 
                        (AD_logFC < -0.5 & LBD_logFC < -0.5) | # down in both
                          (AD_logFC > .5 & LBD_logFC > 0.5) | # up in both
                          (AD_logFC > .5 & LBD_logFC < 0) | # up in AD, down in LBD
                          (AD_logFC < -.5 & LBD_logFC > 0)) # up in LBD, down in AD
ROS1_goi <- subset(ADandLBD, gene_name == "ROS1")
more_goi <- subset(ADandLBD, AD_logFC > .2 & LBD_logFC < -0.2) 

ADandLBD_corr_plot <- ggplot(data = ADandLBD, 
  aes(x = AD_logFC, y = LBD_logFC, text = paste(gene_name))) +
  annotate(
    "rect",
    xmin = 0,
    xmax = 1.75,
    ymin = 1.75,
    ymax = 0,
    fill = "lightpink3",
    alpha = .5
  ) +  annotate(
    "rect",
    xmin = 0,
    xmax = -1.75,
    ymin = 0,
    ymax = -1.75,
    fill = "cadetblue3",
    alpha = .5) +
  geom_abline(color = "gray40") +
  geom_text_repel(
    data = ADandLBD_goi, 
    aes(
      x = AD_logFC, 
      y = LBD_logFC,
      label = gene_name
    ),
    color = "black",
    fontface = "italic",
    size = 2, 
    max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
  ) +
  geom_text_repel(
    data = more_goi, 
    aes(
      x = AD_logFC, 
      y = LBD_logFC,
      label = gene_name
    ),
    color = "black",
    nudge_x = .15,
    nudge_y = -.15,
    fontface = "italic",
    size = 2, 
    max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
  ) +
  geom_point(size = 1) + 
  theme_bw() +
  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.title.y = element_text(size = 8),
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.2, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 0)) +
  labs(
    title = "All expressed genes
Shared between LBD and AD",
    x = expression(paste("  ", log[2](AD/control))),
    y = expression(paste("  ", log[2](LBD/control))))+
  scale_y_continuous(breaks = seq(-1.5, 1.5, by = .5), 
                     limits = c(-1.75, 1.75), expand = c(0,0)) +
  scale_x_continuous(breaks = seq(-1.5, 1.5, by = .5), 
                     limits = c(-1.75, 1.75), expand = c(0,0))
ADandLBD_corr_plot
```
# Volcano - LBD vs AD 
```{r}
i <- "LBDvsAD"
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:7,]
    up10 <- 

    upFold <- subset(up, logFC > 0.9)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:10,]
    downFold <- subset(down, logFC < -0.65)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none", 
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.margin = margin(0.1, 0.3, 0.2, 0.4, "cm"), #t,r,b,l
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      scale_color_manual(values = my_colors) +
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      #theme(plot.title = element_text(size = 7, margin = margin(0,0,0,0))) +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i)) +
      geom_text_repel(
        data = up10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 2,
        x_nudge = 0.5,
        y_nudge = 0.5,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 8)
      ) +
      geom_text_repel(
        data = upFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 2,
        x_nudge = 0.5,
       # y_nudge = 0.5,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 5)
      ) +
      geom_text_repel(
        data = down10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) +
      geom_text_repel(
        data = downFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) +
  scale_x_continuous(limits = c(-1, 1.5), breaks = seq(-1, 1.5, .5))
volcano
i <- gsub(" vs ", "vs", i)
```
# LBD vs AD - metascape 
### Metascape Enrichment - format the dataframes
```{r}
# read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../../../results/",
      tool,
      "/metascape/",
      i,
      "_up_regulated/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../../../results/",
      tool,
      "/metascape/",
      i,
      "_down_regulated/metascape_result.xlsx"
    ), sheet = 2
  )
```

```{r}
# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("up-regulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("down-regulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)

down_enrich_results_subset$Description <-
      gsub(
       "regulation of cysteine-type endopeptidase activity involved in apoptotic process",
        "reg cysteine endopeptidase in apoptotic process",
        down_enrich_results_subset$Description
      )
down_enrich_results_subset$Description <-
      gsub(
       "regulation of protein-containing complex assembly",
        "reg of protein-containing complex assembly",
        down_enrich_results_subset$Description
      )
down_enrich_results_subset$Description <- factor(down_enrich_results_subset$Description, levels = down_enrich_results_subset$Description)

up_enrich_results_subset$Description <-
      gsub(
       "positive regulation of cellular component biogenesis",
       "positive reg of cellular component biogenesis",
        up_enrich_results_subset$Description
      )
up_enrich_results_subset$Description <- factor(up_enrich_results_subset$Description, levels = up_enrich_results_subset$Description)
```

remove files 
```{r}
remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)
```
### Enrichment plot showing log10 P-value
```{r}
# New facet label names for supp variable
Cluster.labs <- c("LBD vs AD
down-regulated")
names(Cluster.labs ) <- c("down-regulated")

# lock in factor level order
down_enrich_results_subset$Description <- factor(down_enrich_results_subset$Description, levels = rev(down_enrich_results_subset$Description))
down_enrich_plot <-
  ggplot(data = down_enrich_results_subset, aes(x = InTerm, y = Description)) +
  ggplot2::facet_grid(~ Cluster, labeller = labeller(Cluster = Cluster.labs)) +
  geom_bar(stat = "identity", aes(fill = LogP), width = .65) +
  theme_bw() +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "Gene count", y = "") +
  guides(fill = guide_legend(
    size = 1,
    title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)")
  )) +
  scale_fill_gradientn(
    colours = c("midnightblue", "blue", "cadetblue1"), # midnightblue
    guide = "legend",
    limits = c(-36,-2),
    breaks = c(-36, -30, -20, -10, -5, -2)
  ) + theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.3, 0.3, 0.2, 0.1, "cm"), 
          plot.title = element_text(size = 8, hjust = 0, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(down_enrich_plot, pointSize = 3, textSize = 6, spaceLegend = .5) {
    down_enrich_plot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.position = "right",
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
# Apply on original plot
down_enrich_plot <- addSmallLegend(down_enrich_plot)
down_enrich_plot


# New facet label names for supp variable
Cluster.labs <- c("LBD vs AD
up-regulated")
names(Cluster.labs ) <- c("up-regulated")

up_enrich_results_subset$Description <- factor(up_enrich_results_subset$Description, levels = rev(up_enrich_results_subset$Description))
up_enrich_plot <-
  ggplot(data = up_enrich_results_subset, aes(x = InTerm, y = Description)) +
  ggplot2::facet_grid(~ Cluster, labeller = labeller(Cluster = Cluster.labs)) +
  geom_bar(stat = "identity", aes(fill = LogP), width = .65) +
  theme_bw() +
  scale_y_discrete(expand = c(0, 0)) +
  labs(x = "Gene count", y = "") +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c("darkred", "red", "lightcoral"),
    guide = "legend",
    limits = c(-20,-5)
  ) +
 theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.3, 0.3, 0.2, 0.3, "cm"), 
          plot.title = element_text(size = 8, hjust = 0, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(up_enrich_plot, pointSize = 3, textSize = 6, spaceLegend = .5) {
    up_enrich_plot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.position = "right",
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
up_enrich_plot <- addSmallLegend(up_enrich_plot)
up_enrich_plot
```

# Combined plots
```{r}
row1 <-
  ggarrange(
    upset_gene,
    shared_up_enric_heatmap,
    ncol = 2,
    labels = c("a)", "b)"),
    font.label = list(size = 8)
  )

row2 <-
  ggarrange(
    shared_down_enric_heatmap,
    ADandLBD_corr_plot_sig,
    ncol = 2,
    labels = c("c)", "d)"),
    font.label = list(size = 8)
  )

row3 <-
  ggarrange(
    ADandLBD_corr_plot,
    volcano,
    ncol = 2,
    labels = c("e)", "f)"),
    font.label = list(size = 8)
  )

row4 <-
  ggarrange(
    up_enrich_plot,
    down_enrich_plot,
    ncol = 2,
    labels = c("g)", "h)"),
    font.label = list(size = 8)
  )

combind <-
  ggarrange(
    row1,
    row2,
    row3,
    row4,
    nrow = 4
  )
combind

path <- paste0("../../../results/manuscript_figures/Figure_3_AD_vs_LBD")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 11)
```
```{r}
```
