---
title: "Figure 5 - sex differences"
author: "Kimberly Olney"
date: "2023-07-13"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
library("readxl")
#source(here::here("scripts/R", "gtf_path.R"))
condition <- c("TYPE.SEX")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))

addSmallLegend <- function(myPlot, pointSize = 4, textSize = 7, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
```
# Volcano 
## LBD vs Control
### XX female
```{r LBD_female_volcano, warning=FALSE}
i <- "female_XX_LBDvsControl"
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:2,]
    upFold <- subset(up, logFC > 1.15)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:4,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
    i <- gsub("_", " ", i)
Female_LBD_vs_control_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 0.85) +
      xlim(-2, 2) +
      ylim(0, 11) +
      theme_bw() +
      theme(legend.position = "none", 
        plot.margin = margin(0.1, 0.2, 0.2, 0.2, "cm"), 
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      scale_color_manual(values = my_colors) +
      ggtitle(paste0("XX Female
LBD vs Control")) +
      labs(
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      #theme(plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
  scale_x_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_y_continuous(limits = c(0, 12), breaks = seq(0, 12, 3))
Female_LBD_vs_control_volcano
i <- gsub(" vs ", "vs", i)
i <- gsub(" ", "_", i)
```
### XY male
```{r LBD_male_volcano, warning=FALSE}
i <- "male_XY_LBDvsControl"
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:4,]
    upFold <- subset(up, logFC > 0.75)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:4,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
    i <- gsub("_", " ", i)
Male_LBD_vs_control_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 0.85) +
      theme_bw() +
        xlim(-2, 2) +
        ylim(0, 11) +
      theme(legend.position = "none", 
        plot.margin = margin(0.1, 0.2, 0.2, 0.2, "cm"), 
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      scale_color_manual(values = my_colors) +
        ggtitle("XY Male
LBD vs Control") +
      labs(
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
  scale_x_continuous(limits = c(-2, 2), breaks = seq(-2, 2, 1)) +
  scale_y_continuous(limits = c(0, 12), breaks = seq(0, 12, 3))
Male_LBD_vs_control_volcano
i <- gsub(" vs ", "vs", i)
i <- gsub(" ", "_", i)
```
## AD vs Control
### XX female
```{r AD_female_volcano, warning=FALSE}
i <- "female_XX_ADvsControl"
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:4,]
    upFold <- subset(up, logFC > 1)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:4,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
    i <- gsub("_", " ", i)
Female_AD_vs_control_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 0.85) +
      xlim(-2.25, 2.5) +
      ylim(0, 9) +
      theme_bw() +
      theme(legend.position = "none", 
        plot.margin = margin(0.1, 0.2, 0.2, 0.2, "cm"), 
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      scale_color_manual(values = my_colors) +
        ggtitle("XX Female
AD vs Control") +
      labs(
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      #theme(plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +

      geom_text_repel(
        data = up10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 2)
      ) +
      geom_text_repel(
        data = upFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 2)
      ) +
      geom_text_repel(
        data = down10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 2)
      ) +
  scale_x_continuous(limits = c(-2.5, 2.5), breaks = seq(-2.5, 2.5, 1)) +
  scale_y_continuous(limits = c(0, 9.5), breaks = seq(0, 9.5, 3))
Female_AD_vs_control_volcano
i <- gsub(" vs ", "vs", i)
i <- gsub(" ", "_", i)
```
### XY male
```{r AD_male_volcano, warning=FALSE}
i <- "male_XY_ADvsControl"
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:4,]
    upFold <- subset(up, logFC > 1)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:4,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
    i <- gsub("_", " ", i)
Male_AD_vs_control_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 0.85) +
      theme_bw() +
        xlim(-2, 2.5) +
        ylim(0, 9) +
      theme_bw() +
      theme(legend.position = "none", 
        plot.margin = margin(0.1, 0.2, 0.2, 0.2, "cm"), 
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      scale_color_manual(values = my_colors) +
        ggtitle("XY Male
AD vs Control") +
      labs(
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      #theme(plot.title = element_text(size = 8, margin = margin(0,0,0,0))) +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_text_repel(
        data = down10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 2)
      ) +
      geom_text_repel(
        data = downFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 2,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 2)
      ) +
  scale_x_continuous(limits = c(-2.5, 2.5), breaks = seq(-2.5, 2.5, 1)) +
  scale_y_continuous(limits = c(0, 9.5), breaks = seq(0, 9.5, 3))
Male_AD_vs_control_volcano
i <- gsub(" vs ", "vs", i)
i <- gsub(" ", "_", i)
```
# Upset of DEGs
Function to create tables
```{r}
fromList <- function (input) {
  # Same as original fromList()...
  elements <- unique(unlist(input))
  data <- unlist(lapply(input, function(x) {
      x <- as.vector(match(elements, x))
      }))
  data[is.na(data)] <- as.integer(0)
  data[data != 0] <- as.integer(1)
  data <- data.frame(matrix(data, ncol = length(input), byrow = F))
  data <- data[which(rowSums(data) != 0), ]
  names(data) <- names(input)
  # ... Except now it conserves your original value names!
  row.names(data) <- elements
  return(data)
}

makePaddedDataFrame <- function(l, ...) {
  maxlen <- max(sapply(l, length))
  data.frame(lapply(l, na.pad, len = maxlen), ...)
}
```
read in data tables
```{r}
allComparisons <- c("LBDvsControl", 
                    "ADvsControl")
allComparisons # check

# XX females only 
coef <- 1
sex_condition <- c("female_XX")
condition <- c("TYPE.SEX")
for (i in allComparisons) {
  filepath <- paste0(
    "../../../results/",
    tool,
    "/DEGs/", condition, "_",  sex_condition, "_",
    i,
    "_gene_DEGs_FDRq1.00.txt"
  )
  assign(paste0(i,"_", sex_condition),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
  # increment
  coef <- coef + 1
}

# XY males only 
coef <- 1
sex_condition <- c("male_XY")
for (i in allComparisons) {
  filepath <- paste0(
    "../../../results/",
    tool,
    "/DEGs/",condition, "_", sex_condition, "_",
    i,
    "_gene_DEGs_FDRq1.00.txt"
  )
  assign(paste0(i,"_", sex_condition),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
  # increment
  coef <- coef + 1
}

# XX females
LBDvsControl_female_XX_up <- subset(LBDvsControl_female_XX, logFC > 0.25 & adj.P.Val <= 0.05)
LBDvsControl_female_XX_down <- subset(LBDvsControl_female_XX, logFC < -0.25 & adj.P.Val <= 0.05)
ADvsControl_female_XX_up <- subset(ADvsControl_female_XX, logFC > 0.25 & adj.P.Val <= 0.05)
ADvsControl_female_XX_down <- subset(ADvsControl_female_XX, logFC < -0.25 & adj.P.Val <= 0.05)

# XY males
LBDvsControl_male_XY_up <- subset(LBDvsControl_male_XY, logFC > 0.25 & adj.P.Val <= 0.05)
LBDvsControl_male_XY_down <- subset(LBDvsControl_male_XY, logFC < -0.25 & adj.P.Val <= 0.05)
ADvsControl_male_XY_up <- subset(ADvsControl_male_XY, logFC > 0.25 & adj.P.Val <= 0.05)
ADvsControl_male_XY_down <- subset(ADvsControl_male_XY, logFC < -0.25 & adj.P.Val <= 0.05)
```
### LBD vs Control bt the sexes 
```{r LBD_upset}
list_input <- list("female down-regulated" = LBDvsControl_female_XX_down$gene_name,
                   "female up-regulated" = LBDvsControl_female_XX_up$gene_name,
                   "male down-regulated" = LBDvsControl_male_XY_down$gene_name,
                   "male up-regulated" = LBDvsControl_male_XY_up$gene_name)
data <- fromList(list_input)

LBD_upset_gene <- upset(data, name='', set_sizes = FALSE,
      c('female down-regulated',
        'male down-regulated',
        'female up-regulated',
        'male up-regulated'),
      themes=upset_modify_themes(
        list('intersections_matrix'=theme(text=element_text(size=10),
              plot.margin = margin(0, 0, 0, 0, "cm")),
          'overall_sizes' = theme(axis.text.x = element_text(size =10), 
               plot.margin = margin(0, 0, 0, 0, "cm")))),
  queries=list(
    upset_query(set='female down-regulated', fill='blue'),
    upset_query(set='male down-regulated', fill='blue'),
    upset_query(set='female up-regulated', fill='red'),
    upset_query(set='male up-regulated', fill='red'),
    upset_query(intersect = c('female down-regulated','male down-regulated'), 
               fill='blue', only_components = 
                  c('intersections_matrix', 'Intersection size')),
    upset_query(intersect = c('female up-regulated','male up-regulated'), 
                fill='red', only_components = 
                  c('intersections_matrix', 'Intersection size'))
  ),
  intersections = list(c('female down-regulated', 'male down-regulated'), 
                       'female down-regulated', 
                       'male down-regulated',
                       c('female up-regulated', 'male up-regulated'), 
                       'female up-regulated', 
                       'male up-regulated',
                       c('female up-regulated', 'male down-regulated')
  ),
  base_annotations=list(
    'Intersection size'=(
        intersection_size(
        size=2,
        text = list(size = 2.5),
        text_mapping = aes(),
        bar_number_threshold=3,  # show all numbers on top of bars
        width=0.3,   # reduce width of the bars
        mapping=aes(fill='bars_color')
      )
      + scale_fill_manual(values=c('grey'), guide='none')
      + scale_y_continuous(expand=expansion(mult=c(0, 0.5)))
      + theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.margin = margin(0, 0, 0, 0.2, "cm"), 
          axis.line=element_line(colour='black')))),
  matrix=intersection_matrix(
      geom=geom_point(
        shape='circle filled',
        size=2,
        stroke=0.45)) +
        theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8), 
              plot.margin = margin(0, 0, 0, 0, "cm")),
    sort_sets=FALSE,
  sort_intersections=FALSE)
LBD_upset_gene
```
### AD vs Control bt the sexes
```{r AD_upset}
list_input <- list("female down-regulated" = ADvsControl_female_XX_down$gene_name,
                   "female up-regulated" = ADvsControl_female_XX_up$gene_name,
                   "male down-regulated" = ADvsControl_male_XY_down$gene_name,
                   "male up-regulated" = ADvsControl_male_XY_up$gene_name)
data <- fromList(list_input)

AD_upset_gene <- upset(data, name = '', set_sizes = FALSE,
      c('female down-regulated',
        'male down-regulated',
        'female up-regulated',
        'male up-regulated'),
      themes=upset_modify_themes(
        list('intersections_matrix'=theme(text=element_text(size=10),
              plot.margin = margin(0, 0, 0, 0, "cm")),
          'overall_sizes' = theme(axis.text.x = element_text(size =10), 
              plot.margin = margin(0, 0, 0, 0, "cm")))),
  queries=list(
    upset_query(set='female down-regulated', fill='blue'),
    upset_query(set='male down-regulated', fill='blue'),
    upset_query(set='female up-regulated', fill='red'),
    upset_query(set='male up-regulated', fill='red'),
    upset_query(intersect = c('female down-regulated','male down-regulated'), 
               fill='blue', only_components = 
                  c('intersections_matrix', 'Intersection size')),
    upset_query(intersect = c('female up-regulated','male up-regulated'), 
                fill='red', only_components = 
                  c('intersections_matrix', 'Intersection size'))
  ),
  intersections = list(c('female down-regulated', 'male down-regulated'), 
                       'female down-regulated', 
                       'male down-regulated',
                       c('female up-regulated', 'male up-regulated'), 
                       'female up-regulated', 
                       'male up-regulated'
  ),
  base_annotations=list(
    'Intersection size'=(
        intersection_size(
        size=2,
        text = list(size = 2.5),
        text_mapping = aes(),
        bar_number_threshold=3,  # show all numbers on top of bars
        width=0.3,   # reduce width of the bars
        mapping=aes(fill='bars_color')
      )
      + scale_fill_manual(values=c('grey'), guide='none')
      + scale_y_continuous(expand=expansion(mult=c(0, 0.5)))
      + theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          plot.margin = margin(0, 0, 0, 0.2, "cm"), 
          axis.line=element_line(colour='black')))),
  matrix=intersection_matrix(
      geom=geom_point(
        shape='circle filled',
        size=2,
        stroke=0.45)) +
        theme(axis.text.y = element_text(size = 8),
              axis.title.y = element_text(size = 8), 
              plot.margin = margin(0, 0, 0, 0, "cm")),
    sort_sets=FALSE,
  sort_intersections=FALSE)
AD_upset_gene
```

# Correlation 
### LBD vs Control bt the sexes
```{r LBD_corr}
LBD_FandM <-
  merge(LBDvsControl_female_XX,
        LBDvsControl_male_XY,
        by = "gene_id",
        all = T)
# remove unnecessary columns 
LBD_FandM <- LBD_FandM[c(7,1,2,6,8:15,22:29)]
colnames(LBD_FandM) = c("gene_name", "gene_id","chr", "gene_type", "female_logFC", "female_CI.L", "female_CI.R", "female_AveExpr", "female_t","female_P.val", "female_adj.P.Val", "female_B", "male_logFC", "male_CI.L", "male_CI.R", "male_AveExpr", "male_t","male_P.val", "male_adj.P.Val", "male_B")

LBD_FandM <- subset(LBD_FandM, (female_adj.P.Val <= 0.05 & female_logFC > 0.25) | 
                      (female_adj.P.Val <= 0.05 & female_logFC < -0.25) |
                    (male_adj.P.Val <= 0.05 & male_logFC > 0.25) |
                    (male_adj.P.Val <= 0.05 & male_logFC < -0.25))
LBD_FandM_goi <- subset(LBD_FandM, 
                               (female_logFC < -0.5 & male_logFC < -0.5) | # down in both 
                               (female_logFC > .5 & male_logFC > 0.5) | # up in both 
                               (female_logFC > .5 & male_logFC <= 0) | # up in females only 
                              (female_logFC <= 0 & male_logFC > 0.5)) # up in males only 

sig_f <- subset(LBD_FandM, female_adj.P.Val <= 0.05 & male_adj.P.Val > 0.05)
sig_m <- subset(LBD_FandM, male_adj.P.Val <= 0.05 & female_adj.P.Val > 0.05)
sig_both <- subset(LBD_FandM, male_adj.P.Val <= 0.05 & female_adj.P.Val <= 0.05)

sig_f_sub <- subset(sig_f, female_logFC > 1 | female_logFC < -1)
sig_m_sub <- subset(sig_m, male_logFC > 1 | male_logFC < -1)
sig_both_sub <- subset(sig_both, male_logFC > 1 | male_logFC < -1 | female_logFC > 1 | female_logFC < -1)

# plot
LBD_corr_plot_adjPval_05 <- ggplot(data = LBD_FandM, 
   aes(x = female_logFC, y = male_logFC, text = paste(gene_name))) +
   annotate(
    "rect",
    xmin = 0,
    xmax = 2,
    ymin = 2,
    ymax = 0,
    fill = "lightpink3",
    alpha = .1
  ) +  annotate(
    "rect",
    xmin = 0,
    xmax = -1.75,
    ymin = 0,
    ymax = -1.75,
    fill = "cadetblue3",
    alpha = .1) +
  geom_abline(color = "gray80", linetype = 2) +
  geom_point(data = sig_f, color="#490092", shape=16) + 
  geom_point(data = sig_m, color="#D55E00", shape=15) + 
  geom_point(data = sig_both, color="gray20", shape=25) + 
  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.4, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 0)) +
  labs(
  title = "Differentially expressed genes, FDRq < 0.05 & absolute log2FC > 0.25
Shared and unique between the sexes",
  x = expression(paste("XX female ", log[2](LBD/control))),
  y = expression(paste("XY male ", log[2](LBD/control))))+
  scale_y_continuous(breaks = seq(-1.5, 2, by = .5), 
                     limits = c(-1.75, 2), expand = c(0,0)) +
  scale_x_continuous(breaks = seq(-1.5, 2, by = .5), 
                     limits = c(-1.75, 2), expand = c(0,0))
LBD_corr_plot_adjPval_05 
```
### AD vs Control bt the sexes
```{r AD_corr}
AD_FandM <-
  merge(ADvsControl_female_XX,
        ADvsControl_male_XY,
        by = "gene_id",
        all = T)
# remove unnecessary columns 
AD_FandM <- AD_FandM[c(7,1,2,6,8:15,22:29)]
colnames(AD_FandM) = c("gene_name", "gene_id","chr", "gene_type", "female_logFC", "female_CI.L", "female_CI.R", "female_AveExpr", "female_t","female_P.val", "female_adj.P.Val", "female_B", "male_logFC", "male_CI.L", "male_CI.R", "male_AveExpr", "male_t","male_P.val", "male_adj.P.Val", "male_B")
# significant only 
AD_FandM <- subset(AD_FandM, (female_adj.P.Val <= 0.05 & female_logFC > 0.25) | 
                      (female_adj.P.Val <= 0.05 & female_logFC < -0.25) |
                    (male_adj.P.Val <= 0.05 & male_logFC > 0.25) |
                    (male_adj.P.Val <= 0.05 & male_logFC < -0.25))
AD_FandM_goi <- subset(AD_FandM, 
                               (female_logFC < -0.5 & male_logFC < -0.5) | # down in both 
                               (female_logFC > .5 & male_logFC > 0.5) | # up in both 
                               (female_logFC > .5 & male_logFC <= 0) | # up in females only 
                              (female_logFC <= 0 & male_logFC > 0.5)) # up in males only 

sig_f <- subset(AD_FandM, female_adj.P.Val <= 0.05 & male_adj.P.Val > 0.05)
sig_m <- subset(AD_FandM, male_adj.P.Val <= 0.05 & female_adj.P.Val > 0.05)
sig_both <- subset(AD_FandM, male_adj.P.Val <= 0.05 & female_adj.P.Val <= 0.05)

sig_f_sub <- subset(sig_f, female_logFC > 1 | female_logFC < -1)
sig_m_sub <- subset(sig_m, male_logFC > 1 | male_logFC < -1)
sig_both_sub <- subset(sig_both, male_logFC > 1 | male_logFC < -1 | female_logFC > 1 | female_logFC < -1)

# plot
AD_corr_plot_adjPval_05 <- ggplot(data = AD_FandM, 
   aes(x = female_logFC, y = male_logFC, text = paste(gene_name))) +
   annotate(
    "rect",
    xmin = 0,
    xmax = 2.5,
    ymin = 2.5,
    ymax = 0,
    fill = "lightpink3",
    alpha = .1
  ) +  annotate(
    "rect",
    xmin = 0,
    xmax = -2,
    ymin = 0,
    ymax = -2,
    fill = "cadetblue3",
    alpha = .1) +
  geom_abline(color = "gray80", linetype = 2) +
  geom_point(data = sig_f, color="#490092", shape=16) + 
  geom_point(data = sig_m, color="#D55E00", shape=15) + 
  geom_point(data = sig_both, color="gray20", shape=25) + 
  theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.title.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.4, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 0)) +
  labs(
  title = "Differentially expressed genes, FDRq < 0.05 & absolute log2FC > 0.25
Shared and unique between the sexes",
  x = expression(paste("XX female ", log[2](AD/control))),
  y = expression(paste("XY male ", log[2](AD/control))))+
  scale_y_continuous(breaks = seq(-1.5, 2.5, by = .5), 
                     limits = c(-2, 2.5), expand = c(0,0)) +
  scale_x_continuous(breaks = seq(-1.5, 2.5, by = .5), 
                     limits = c(-2, 2.5), expand = c(0,0))
AD_corr_plot_adjPval_05 


```
# Heatmap 
### LBD
```{r}
LBD_FandM$difference <- LBD_FandM$female_logFC - LBD_FandM$male_logFC

LBD_FandM <- subset(LBD_FandM, difference > .8 | difference < -.8)
LBD_FandM <- LBD_FandM[order(-LBD_FandM$difference),]
LBD_FandM_DEGs_melt <- reshape2::melt(LBD_FandM)
data <- subset(LBD_FandM_DEGs_melt, variable == "female_logFC" | variable == "male_logFC")
data$gene_name <- factor(data$gene_name , levels = unique(data$gene_name))
data$gene_name <- fct_rev(data$gene_name)
data$variable <- factor(data$variable)

data$variable <- gsub("female_logFC", "XX Female", data$variable)
data$variable <- gsub("male_logFC", "XY Male", data$variable)

data$colorVal <-  ifelse(data$value > -.5, 'black', "white")

LBD_heatmap <- ggplot(data = data) +
  geom_tile(aes(x = variable, y =gene_name, fill = value)) +
  geom_text(aes(x = variable, y =gene_name, label = round(value, digits = 2), color = colorVal), size = 2.5) +
  scale_color_manual(values = c('black' = 'black', 'white' = 'white'), guide = "none") +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-1,0,2)),
                         guide = "colorbar", limits=c(-1, 2),
                         breaks = c(-1, 0, 2), name = expression(log[2](FC))) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 0.3, 0.2, 0.8, "cm"), #t,r,b,l
    plot.title = element_text(size = 8, margin = margin(.1,.1,.1,0), hjust = 0),
    panel.spacing = unit(0,'lines'), 
   # plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_blank(),
    axis.ticks.x=element_blank(), 
    axis.text.x = element_text(size = 8, color = "black"),
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank()) +
  ggtitle("Genes with the largest difference between the sexes
LBD vs Control within each sex") +
    theme(
    legend.position = "right", 
    legend.text = element_text(size =6), 
    legend.title = element_text (size = 8), 
    legend.margin=margin(0,0,1,0),
    legend.key.size = unit(0.5, "cm"))
LBD_heatmap <- addSmallLegend(LBD_heatmap)
```
### AD
```{r}
AD_FandM$difference <- AD_FandM$female_logFC - AD_FandM$male_logFC

AD_FandM <- subset(AD_FandM, difference > 1.1 | difference < -.8)
AD_FandM <- AD_FandM[order(-AD_FandM$difference),]
AD_FandM_DEGs_melt <- reshape2::melt(AD_FandM)
data <- subset(AD_FandM_DEGs_melt, variable == "female_logFC" | variable == "male_logFC")
data$gene_name <- factor(data$gene_name , levels = unique(data$gene_name))
data$gene_name <- fct_rev(data$gene_name)
data$variable <- factor(data$variable)

data$variable <- gsub("female_logFC", "XX Female", data$variable)
data$variable <- gsub("male_logFC", "XY Male", data$variable)

data$colorVal <-  ifelse(data$value > -.5, 'black', "white")

AD_heatmap <- ggplot(data = data) +
  geom_tile(aes(x = variable, y =gene_name, fill = value)) +
  geom_text(aes(x = variable, y =gene_name, label = round(value, digits = 2), color = colorVal), size = 2.5) +
  scale_color_manual(values = c('black' = 'black', 'white' = 'white'), guide = "none") +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-1.3,0,2.35)),
                         guide = "colorbar", limits=c(-1.3, 2.35),
                         breaks = c(-1.3, 0, 2.35), name = expression(log[2](FC))) +
  scale_x_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 0.6, 0.2, 0.6, "cm"), #t,r,b,l
    plot.title = element_text(size = 8, margin = margin(.1,.3,.1,0), hjust = 0),
    panel.spacing = unit(0,'lines'), 
   # plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_blank(),
    axis.text.x = element_text(size = 8, color = "black"),
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank()) +
  ggtitle("Genes with the largest difference between the sexes
AD vs Control within each sex") +
  theme(
    legend.position = "right", 
    legend.text = element_text(size =6), 
    legend.title = element_text (size = 8), 
    legend.margin=margin(0,0,1,0),
    legend.key.size = unit(0.5, "cm"))
AD_heatmap <- addSmallLegend(AD_heatmap)
AD_heatmap
```
# Gene-level combine all plots 
```{r}
row1 <-
  ggarrange(
    Female_LBD_vs_control_volcano,
    Male_LBD_vs_control_volcano,
    LBD_upset_gene,
    ncol = 3,
    labels = c("a)", "b)", "c)"),
    font.label = list(size = 8),
    widths = c(.8, .8, 1.2)
  )

row2 <- ggarrange(
  LBD_corr_plot_adjPval_05,
  LBD_heatmap,
  ncol = 2,
  labels = c("d)", "e)"),
  font.label = list(size = 8),
  widths = c(1.2, .9)
  )

row3 <-
  ggarrange(
    Female_AD_vs_control_volcano,
    Male_AD_vs_control_volcano,
    AD_upset_gene,
    ncol = 3,
    labels = c("f)", "g)", "h)"),
    font.label = list(size = 8),
    widths = c(.8, .8, 1.2)
  )

row4 <- ggarrange(
  AD_corr_plot_adjPval_05,
  AD_heatmap,
  ncol = 2,
  labels = c("i)", "j)"),
  font.label = list(size = 8),
  widths = c(1.2, .9)
  )

combind <-
  ggarrange(
    row1,
    row2,
    row3,
    row4,
    nrow = 4
  )
combind

path <- paste0("../../../results/manuscript_figures/Figure_5_sex_differences")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 11)

#jpeg(file="../../../results/manuscript_figures/Figure_5_sex_differences.jpeg",
#width=8, height=11, units="in", res = 1500)
#combind
#dev.off()
```

```{r}
```

