---
title: "Figure 4 - gene networks"
author: "Kimberly Olney"
date: "2023-07-13"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("/research/labs/neurology/fryer/m239830/LBD_CWOW/scripts/R", "file_paths_and_colours.R"))
library("readxl")
library(WGCNA)
library(anRichmentMethods)
library(tidyverse)
library(CorLevelPlot)
library(gridExtra)
library("limmaDE2")
#devtools::install_github('thomasp85/ggraph')
library(ggraph)
detach("package:enrichplot", unload = TRUE)

condition <- c("TYPE")
tool <- "star"

addSmallLegend <- function(myPlot, pointSize = 4, textSize = 7, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}
```
# Read in data
```{r}
voomCounts <- readRDS(paste0("../../../rObjects/", condition, ".voomCountsMatrix.rds"))
load("../../../rObjects/bwnet.Rdata")
load("../../../rObjects/WGCNA_allSampleInput.RData")
module_eigengenes <- bwnet$MEs
head(module_eigengenes) # inspect 
ngenes_per_module <- table(bwnet$colors) # number of genes in each module 

dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))
info <- as.data.frame(dge.filtered.norm$samples)
genes <- as.data.frame(dge.filtered.norm$genes)

# keep only the columns that hold information we need. 
dataTraits <- info[, c(6,11:19,21,22,24,29,37,108,109,114,117:124)] # Keep
dim(dataTraits)
# disease type isn't numeric, make numeric as this is required down stream
numeric_traits <- sapply(dataTraits, as.numeric)
numeric_traits <- as.data.frame(numeric_traits) # save as data frame
rownames(numeric_traits) <- rownames(dataTraits) # add NPID as row names
```
# igraph
### DEGs
```{r}
# First read in DEGs from limma/voom 
# read in DEGs 
LBDvsControl <- read.delim("../../../results/star/DEGs/TYPE_LBDvsControl_gene_DEGs_FDRq0.05_logFC_0.25.txt")
ADvsControl <- read.delim("../../../results/star/DEGs/TYPE_ADvsControl_gene_DEGs_FDRq0.05_logFC_0.25.txt")
# PAvsControl <- read.delim("../../../results/star/DEGs/TYPE_PAvsControl_gene_DEGs_FDRq0.05_logFC_0.25.txt")
LBDvsAD <- read.delim("../../../results/star/DEGs/TYPE_LBDvsAD_gene_DEGs_FDRq0.05_logFC_0.25.txt")

# plot
# Genes in modules
color_counts <- as.data.frame(bwnet$colors) # color modules 
color_counts$gene_id <- row.names(color_counts) # gene_ids as row names
colnames(color_counts)[1] ="hcolors"

heatmap.data <- merge(module_eigengenes, numeric_traits, by = "row.names")
heatmap.data <- heatmap.data %>%
  column_to_rownames(var = 'Row.names')

# some data has missing values with na, such as lewy body count. 
# Replace na with zero 
heatmap.data["Cing.LB"][is.na(heatmap.data["Cing.LB"])] <- 0
heatmap.data["Cing.Synuclein"][is.na(heatmap.data["Cing.Synuclein"])] <- 0
plot_colors <- names(heatmap.data)[1:15]
plot_colors <- gsub("ME", "", plot_colors)
color_counts$hcolors <- factor(color_counts$hcolors, levels = rev(plot_colors)) # arrange to match previous plot 

### AD vs Control
df_ADvsControl <- merge(color_counts, ADvsControl, by = "gene_id", all = TRUE)
df_ADvsControl$FDRq <- ifelse(df_ADvsControl$adj.P.Val < 0.05, "< 0.05", "No difference")
df_ADvsControl$FDRq <- df_ADvsControl$FDRq %>% replace_na('Not DE')
colnames(df_ADvsControl)[2] ="hcolors"
#### LBD vs Control
df_LBDvsControl <- merge(color_counts, LBDvsControl, by = "gene_id", all = TRUE)
df_LBDvsControl$FDRq <- ifelse(df_LBDvsControl$adj.P.Val < 0.05, "< 0.05", "No difference")
df_LBDvsControl$FDRq <- df_LBDvsControl$FDRq %>% replace_na('Not DE')
colnames(df_LBDvsControl)[2] ="hcolors"
#### LBD vs AD
df_LBDvsAD <- merge(color_counts, LBDvsAD, by = "gene_id", all = TRUE)
df_LBDvsAD$FDRq <- ifelse(df_LBDvsAD$adj.P.Val < 0.05, "< 0.05", "No difference")
df_LBDvsAD$FDRq <- df_LBDvsAD$FDRq %>% replace_na('Not DE')
colnames(df_LBDvsAD)[2] ="hcolors"

data <- df_ADvsControl %>% 
  group_by(FDRq,hcolors) %>%
  dplyr::count() %>% 
  ungroup(FDRq) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
data$perc <- data$perc*100
data$hcolors <- factor(data$hcolors, levels = plot_colors) 
data$FDRq <- factor(data$FDRq, levels = c("Not DE", "< 0.05"))

ADvsControl_per_DEGs <- ggplot(data, aes(fill=FDRq, y=hcolors, x=perc)) + 
    geom_bar(position="fill", stat="identity") +
 theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8, margin = margin(t = 0, r = 10, b = 0, l = 0)),
          axis.title.y = element_blank(), 
          axis.text.x = element_text(size = 8, color = "black", angle = 45, vjust = 1, hjust=1), 
          axis.title.x = element_blank(), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.4,0)),
          legend.position = "right", 
          legend.text = element_text(size =6), 
          legend.title = element_text (size = 8), 
          legend.margin=margin(0,0,1,0),
          legend.key.size = unit(0.5, "cm")) +
  ggtitle("AD vs Control") +
    xlab("Portion") +
    ylab("Gene modules") +
  scale_fill_manual("legend", values = c("< 0.05" = "salmon", "Not DE" = "grey65")) +
  theme(legend.position="none")
ADvsControl_per_DEGs


#### LBD vs Control
df_LBDvsControl <- merge(color_counts, LBDvsControl, by = "gene_id", all = TRUE)
df_LBDvsControl$FDRq <- ifelse(df_LBDvsControl$adj.P.Val < 0.05, "< 0.05", "No difference")
df_LBDvsControl$FDRq <- df_LBDvsControl$FDRq %>% replace_na('Not DE')
colnames(df_LBDvsControl)[2] ="hcolors"

data <- df_LBDvsControl %>% 
  group_by(FDRq,hcolors) %>%
  dplyr::count() %>% 
  ungroup(FDRq) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
data$perc <- data$perc*100
data$hcolors <- factor(data$hcolors, levels = plot_colors) 
data$FDRq <- factor(data$FDRq, levels = c("Not DE", "< 0.05"))

LBDvsControl_per_DEGs <- ggplot(data, aes(fill=FDRq, y=hcolors, x=perc)) + 
    geom_bar(position="fill", stat="identity") +
 theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8, margin = margin(t = 0, r = 10, b = 0, l = 0)),
          axis.title.y = element_blank(), 
          axis.text.x = element_text(size = 8, color = "black", angle = 45, vjust = 1, hjust=1), 
          axis.title.x = element_blank(), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.4,0)),
          legend.position = "right", 
          legend.text = element_text(size =6), 
          legend.title = element_text (size = 8), 
          legend.margin=margin(0,0,1,0),
          legend.key.size = unit(0.5, "cm")) +
  ggtitle("LBD vs Control ") +
    xlab("Portion") +
    ylab("Gene modules") +
  scale_fill_manual("legend", values = c("< 0.05" = "salmon", "Not DE" = "grey65"))+
  theme(legend.position="none")
LBDvsControl_per_DEGs


#### LBD vs AD
df_LBDvsAD <- merge(color_counts, LBDvsAD, by = "gene_id", all = TRUE)
df_LBDvsAD$FDRq <- ifelse(df_LBDvsAD$adj.P.Val < 0.05, "< 0.05", "No difference")
df_LBDvsAD$FDRq <- df_LBDvsAD$FDRq %>% replace_na('Not DE')
colnames(df_LBDvsAD)[2] ="hcolors"

data <- df_LBDvsAD %>% 
  group_by(FDRq,hcolors) %>%
  dplyr::count() %>% 
  ungroup(FDRq) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
data$perc <- data$perc*100
data$hcolors <- factor(data$hcolors, levels = plot_colors) 

data$FDRq <- factor(data$FDRq, levels = c("Not DE", "< 0.05"))
LBDvsAD_per_DEGs <- ggplot(data, aes(fill=FDRq, y=hcolors, x=perc)) + 
    geom_bar(position="fill", stat="identity") +
 theme_bw() +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8, margin = margin(t = 0, r = 10, b = 0, l = 0)),
          axis.title.y = element_blank(), 
          axis.text.x = element_text(size = 8, color = "black", angle = 45, vjust = 1, hjust=1), 
          axis.title.x = element_blank(), 
          plot.margin = margin(0.1, 0.3, 0.2, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, margin = margin(.1,.1,.4,0)),
          legend.position = "right", 
          legend.text = element_text(size =6), 
          legend.title = element_text (size = 8), 
          legend.margin=margin(0,0,1,0),
          legend.key.size = unit(0.5, "cm")) +
  ggtitle("LBD vs AD ") +
    xlab("Portion") +
    ylab("Gene modules") +
  scale_fill_manual("legend", values = c("< 0.05" = "salmon", "Not DE" = "grey65"))
LBDvsAD_per_DEGs
```
### magenta graph all 
```{r eval = FALSE}
# make the graph
magenta_graph <- wgcna2igraph(net = bwnet, datExpr = counts,
                    modules2plot = c("magenta"),
                    colors2plot = c("magenta"),
                    kME.threshold = 0.75, adjacency.threshold = 0.1,
                    adj.power = 12, verbose = T,
                    node.size = 0, frame.color = NA, node.color = NA,
                    edge.alpha = .5, edge.width =1, returnNet = TRUE)
# Add gene names 
magenta_genes <- genes[c(genes$gene_id %in% V(magenta_graph)$name),]
V(magenta_graph)$gene_name <- magenta_genes$gene_name
# generic plot 
# plot(magenta_graph, edge.arrow.size=.2, edge.color="magenta",
#     vertex.color="magenta", vertex.frame.color="#ffffff",
#     vertex.label=V(magenta_graph)$gene_name, vertex.label.color="black") 

# Get the DEGs for labeling 
# LBD vs Control
LBD_graph_DEGs <- subset(df_LBDvsControl, hcolors == "magenta" & FDRq == "< 0.05")
AD_graph_DEGs <- subset(df_ADvsControl, hcolors == "magenta" & FDRq == "< 0.05")
BTOH <- intersect(LBD_graph_DEGs$gene_name, AD_graph_DEGs$gene_name)
graph_DEGs <- rbind(LBD_graph_DEGs, AD_graph_DEGs)
AD_graph_DEGs$gene_name !%in% BTOH

# Set a selection column 
V(magenta_graph)$selection <- V(magenta_graph)$gene_name %in% graph_DEGs$gene_name

# subset the graph 
DEG_graph <- subgraph.edges(graph=magenta_graph, eids=which(V(magenta_graph)$selection == "TRUE"), delete.vertices = FALSE)

# Plot all 


# plot using ggraph
# Sig in AD or LBD 
V(magenta_graph)$AD <- V(magenta_graph)$gene_name %in% AD_graph_DEGs$gene_name
V(magenta_graph)$LBD <- V(magenta_graph)$gene_name %in% LBD_graph_DEGs$gene_name
V(magenta_graph)$BOTH <- V(magenta_graph)$gene_name %in% BTOH


V(magenta_graph)$AD_fold_change <- AD_graph_DEGs$logFC
library(tidygraph)
graph <- as_tbl_graph(magenta_graph) %>% 
    mutate(AD_graph_DEGs$logFC = centrality_degree(mode = 'in'))


# Loop through the attribute dataframe to add an attribute at the time, using the set_vertex_attribute function. 

for (i in 2:length(AD_graph_DEGs)){
  # Select attributes
  temp_attribute <- AD_graph_DEGs[,c(1,i)]
  # Match the attribute id with the id of the graph vertexes
  sorted_attr<- temp_attribute[match(temp_attribute[,1], V(magenta_graph)$gene_name),2]
  # Set attributes
  magenta_graph <- set_vertex_attr(magenta_graph, name = (names(AD_graph_DEGs)[i]), 
                  index = V(magenta_graph), value = sorted_attr)

}
ggraph(magenta_graph, layout = 'linear', circular = TRUE) + 
    geom_edge_fan(aes(alpha = after_stat(index)), show.legend = FALSE) + 
   # geom_node_point(aes(size = Popularity)) + # add log2FC for size 
    geom_node_text(aes(filter=LBD == TRUE, label = gene_name), size = 5, color = LBD_color, 
                   fontface = "italic") +
    geom_node_text(aes(filter=AD == TRUE, label = gene_name), size = 5, color = AD_color) +
   # facet_edges(~) + # facet by sig in AD vs sig in LBD?
    theme_graph(foreground = 'magenta', fg_text_colour = 'white')

set.seed(1)
ggraph(magenta_graph, 'circlepack', weight = size) + 
  geom_edge_link() + 
  geom_node_point(aes(colour = logFC)) +
  coord_fixed()
```
# Sratch
```{r}
test <- ggraph(magenta_graph, layout = 'nicely') + 
    geom_edge_fan(aes(alpha = after_stat(index)), show.legend = FALSE) + 
   geom_edge_link(colour = "magenta") + 
  # geom_node_point(aes(filter=LBD == TRUE)) +
   # geom_edge_link(colour = "magenta") +
  #  geom_edge_link(aes(filter= AD == TRUE), color = AD_color) +
  # scale_edge_width(range = c(1,1)) +
  # geom_node_text(aes(label = gene_name), size = 3) + # label all genes 
    geom_node_text(aes(filter=LBD == TRUE, label = gene_name), size = 5, color = LBD_color, 
                   fontface = "italic") +
    geom_node_text(aes(filter=AD == TRUE, label = gene_name), size = 5, color = AD_color) +
    theme_graph(foreground = 'white', fg_text_colour = 'white') +
      theme(legend.position = "none", 
             plot.margin = margin(0.1, 0.3, 0.2, 0.4, "cm"), #t,r,b,l
             plot.title = element_text(size = 8, margin = margin(0,0,0,0))) 
test +  guides(edge_color = guide_legend(override.aes = list(edge_width = 5)),
         edge_width = F) 
```

```{r test_loop}
module_colors <- unique(bwnet$colors)
module_colors <- module_colors[module_colors != "grey"] # too large to be meaningful 

module_colors <- c("cyan")
for (i in module_colors) {
set.seed(28)
module_graph <- wgcna2igraph(net = bwnet, datExpr = counts,
                    modules2plot = i,
                    colors2plot = i,
                    kME.threshold = 0.75, adjacency.threshold = 0.1,
                    adj.power = 12, verbose = T,
                    node.size = 0, frame.color = NA, node.color = NA,
                    edge.alpha = .5, edge.width =1)
#-- all network with all gene names 
# Add gene names 
module_genes <- genes[c(genes$gene_id %in% V(module_graph)$name),]
V(module_graph)$gene_name <- module_genes$gene_name
plot(module_graph, edge.arrow.size=.2, edge.color=i,
     vertex.color=i, vertex.frame.color="#ffffff",
     vertex.label=V(module_graph)$gene_name, vertex.label.color="black") 
path <- paste0("../../../results/star/WGCNA/network_graphs/", i)
saveToPDF(paste0(path, ".pdf"), width = 8, height = 8)


# LBD vs Control
graph_DEGs <- subset(df_LBDvsControl, hcolors == i & FDRq == "< 0.05")
V(module_graph)$selection <- V(module_graph)$gene_name %in% graph_DEGs$gene_name
DEG_graph <- subgraph.edges(graph=module_graph, eids=which(V(module_graph)$selection == "TRUE"), delete.vertices = TRUE)
g <- plot(DEG_graph, edge.arrow.size=.2, edge.color=i,
     vertex.color=i, vertex.frame.color="#ffffff",
     vertex.label=V(DEG_graph)$gene_name, vertex.label.color="black", 
     edge.label=NULL, 
     vertex.label.font = ifelse(V(DEG_graph)$selection == "TRUE", 2, 1)) 

plot(DEG_graph, vertex.label = ifelse(V(DEG_graph)$selection == "TRUE", V(DEG_graph)$gene_name, "."), vertex.label.color="black")

path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_LBDvsControl_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 5, height = 5)
ggsave(paste0(plotName, ".png),

plot(DEG_graph, vertex.label = ifelse(V(DEG_graph)$selection == "TRUE", V(DEG_graph)$gene_name, NA), vertex.label.color="black", vertex.label.font = 2)

plot(module_graph, vertex.label = ifelse(V(module_graph)$selection == "TRUE", V(module_graph)$gene_name, NA), vertex.label.color="black")
path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_all_network_LBDvsControl_DEGs_gene_labels")
saveToPDF(paste0(path, ".pdf"), width = 6, height = 6)
remove(graph_DEGs)

# AD vs Control
graph_DEGs <- subset(df_ADvsControl, hcolors == i & FDRq == "< 0.05")
V(module_graph)$selection <- V(module_graph)$gene_name %in% graph_DEGs$gene_name
DEG_graph <- subgraph.edges(graph=module_graph, eids=which(V(module_graph)$selection == "TRUE"), delete.vertices = TRUE)
plot(DEG_graph, edge.arrow.size=.2, edge.color=i,
     vertex.color=i, vertex.frame.color="#ffffff",
     vertex.label=V(DEG_graph)$gene_name, vertex.label.color="black", 
     edge.label=NULL) 
path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_ADvsControl_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 5, height = 5)
plot(module_graph, vertex.label = ifelse(V(module_graph)$selection == "TRUE", V(module_graph)$gene_name, "."), vertex.label.color="black")
path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_all_network_ADvsControl_DEGs_gene_labels")
saveToPDF(paste0(path, ".pdf"), width = 6, height = 6)
remove(graph_DEGs)

# LBD vs AD
graph_DEGs <- subset(df_LBDvsAD, hcolors == i & FDRq == "< 0.05")
V(module_graph)$selection <- V(module_graph)$gene_name %in% graph_DEGs$gene_name
DEG_graph <- subgraph.edges(graph=module_graph, eids=which(V(module_graph)$selection == "TRUE"), delete.vertices = TRUE)
plot(DEG_graph, edge.arrow.size=.2, edge.color=i,
     vertex.color=i, vertex.frame.color="#ffffff",
     vertex.label=V(DEG_graph)$gene_name, vertex.label.color="black", 
     edge.label=NULL) 
path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_LBDvsAD_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 5, height = 5)

plot(module_graph, vertex.label = ifelse(V(module_graph)$selection == "TRUE", V(module_graph)$gene_name, NA), vertex.label.color="black")
path <- paste0("../../../results/star/WGCNA/network_graphs/", i, "_all_network_LBDvsAD_DEGs_gene_labels")
saveToPDF(paste0(path, ".pdf"), width = 6, height = 6)

remove(graph_DEGs, module_graph)
}
```
### magenta subset to only DEGs LBD vs AD 
```{r eval = FALSE}
set.seed(28)
magenta_DEGs <- subset(df_LBDvsControl, hcolors == "magenta" & FDRq == "< 0.05")

V(magenta_graph)$selection <- V(magenta_graph)$gene_name %in% magenta_DEGs$gene_name

magenta_DEG_graph <- subgraph.edges(graph=magenta_graph, eids=which(V(magenta_graph)$selection == "TRUE"), delete.vertices = TRUE)
plot(magenta_DEG_graph)
plot(magenta_DEG_graph, edge.arrow.size=.2, edge.color="magenta",
     vertex.color="magenta", vertex.frame.color="#ffffff",
     vertex.label=V(magenta_DEG_graph)$gene_name, vertex.label.color="black", 
     edge.label=NULL) 
path <- paste0("../../../results/manuscript_figures/magenta_LBDvsControl_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 5, height = 5)

plot(magenta_graph, vertex.label = ifelse(V(magenta_graph)$selection == "TRUE", V(magenta_DEG_graph)$gene_name, NA))

```
### Salmon graph all 
```{r eval = FALSE}
salmon_graph <- wgcna2igraph(net = bwnet, datExpr = counts,
                    modules2plot = c("salmon"),
                    colors2plot = c("salmon"),
                    kME.threshold = 0.75, adjacency.threshold = 0.1,
                    adj.power = 12, verbose = T,
                    node.size = 0, frame.color = NA, node.color = NA,
                    edge.alpha = .5, edge.width =1)
# Add gene names 
salmon_genes <- genes[c(genes$gene_id %in% V(salmon_graph)$name),]
V(salmon_graph)$gene_name <- salmon_genes$gene_name
plot(salmon_graph, edge.arrow.size=.2, edge.color="salmon",
     vertex.color="salmon", vertex.frame.color="#ffffff",
     vertex.label=V(salmon_graph)$gene_name, vertex.label.color="black") 
path <- paste0("../../../results/manuscript_figures/salmon_LBDvsAD_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 4, height = 4)

```
### Salmon subset to only DEGs LBD vs AD 
```{r eval = FALSE}
salmon_DEGs <- subset(df_LBDvsAD, hcolors == "salmon" & FDRq == "< 0.05")

V(salmon_graph)$selection <- V(salmon_graph)$gene_name %in% salmon_DEGs$gene_name

salmon_DEG_graph <- subgraph.edges(graph=salmon_graph, eids=which(V(salmon_graph)$selection == "TRUE"), delete.vertices = TRUE)
plot(salmon_DEG_graph)
plot(salmon_DEG_graph, edge.arrow.size=.2, edge.color="salmon",
     vertex.color="salmon", vertex.frame.color="#ffffff",
     vertex.label=V(salmon_DEG_graph)$gene_name, vertex.label.color="black", 
     edge.label=NULL) 
path <- paste0("../../../results/manuscript_figures/salmon_LBDvsAD_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 4, height = 4)
```
#### green
```{r eval = FALSE}
green_graph <- wgcna2igraph(net = bwnet, datExpr = counts,
                    modules2plot = c("green"),
                    colors2plot = c("green"),
                    kME.threshold = 0.75, adjacency.threshold = 0.1,
                    adj.power = 12, verbose = T,
                    node.size = 0, frame.color = NA, node.color = NA,
                    edge.alpha = .5, edge.width =1)
# Add gene names 
green_genes <- genes[c(genes$gene_id %in% V(green_graph)$name),]
V(green_graph)$gene_name <- green_genes$gene_name
plot(green_graph, edge.arrow.size=.2, edge.color="green",
     vertex.color="green", vertex.frame.color="#ffffff",
     vertex.label=V(green_graph)$gene_name, vertex.label.color="black") 
path <- paste0("../../../results/manuscript_figures/green")
saveToPDF(paste0(path, ".pdf"), width = 12, height = 12)

green_DEGs <- subset(df_LBDvsAD, hcolors == "green" & FDRq == "< 0.05")
V(green_graph)$selection <- V(green_graph)$gene_name %in% green_DEGs$gene_name
green_DEG_graph <- subgraph.edges(graph=green_graph, eids=which(V(green_graph)$selection == "TRUE"), delete.vertices = TRUE)
plot(green_DEG_graph)
plot(green_DEG_graph, edge.arrow.size=.2, edge.color="green",
     vertex.color="green", vertex.frame.color="#ffffff",
     vertex.label=V(gbf)$gene_name, vertex.label.color="black", 
     edge.label=NULL) 
path <- paste0("../../../results/manuscript_figures/green_LBDvsAD_DEGs")
saveToPDF(paste0(path, ".pdf"), width = 4, height = 4)
```
# Combine all plots 
```{r}
row1 <- ggarrange(
  ADvsControl_per_DEGs, 
  LBDvsControl_per_DEGs,
  test,
  ncol = 3, 
  widths = c(.8, .8, 1.2)
  
)
ggarrange(
  row1,
  NULL,
  NULL, 
  nrow = 3
)
path <- paste0("/research/labs/neurology/fryer/m239830/LBD_CWOW/results/manuscript_figures/Figure_6_networks")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 11)
```
```{r}
```
