---
title: "Figure 3. within LBD comparisons"
author: "Kimberly Olney"
date: "07/10/2023"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
library("readxl")
#source(here::here("scripts/R", "gtf_path.R"))
condition <- c("TYPE")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))
```
# Binary list shared gene function
```{r}
fromList <- function (input) {
  # Same as original fromList()...
  elements <- unique(unlist(input))
  data <- unlist(lapply(input, function(x) {
      x <- as.vector(match(elements, x))
      }))
  data[is.na(data)] <- as.integer(0)
  data[data != 0] <- as.integer(1)
  data <- data.frame(matrix(data, ncol = length(input), byrow = F))
  data <- data[which(rowSums(data) != 0), ]
  names(data) <- names(input)
  # ... Except now it conserves your original value names!
  row.names(data) <- elements
  return(data)
  }
```
# Metascape Enrichment 
### Format the dataframes
```{r}
i <- "LBDvsControl"
# read in enrichment analysis results
up_enrich_results <-
  read_excel(
    paste0(
      "../../../results/",
      tool,
      "/metascape/",
      i,
      "_up_regulated/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../../../results/",
      tool,
      "/metascape/",
      i,
      "_down_regulated/metascape_result.xlsx"
    ), sheet = 2
  )
```

```{r}
# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary", 
    "15_Summary", 
    "16_Summary",
    "17_Summary", 
    "18_Summary", 
    "19_Summary",  
    "20_Summary" 
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("up-regulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("down-regulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)

# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset, down_enrich_results_subset)

up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
up_and_down_enrich_results_subset$Cluster <- factor(up_and_down_enrich_results_subset$Cluster, levels = c("up-regulated", "down-regulated"))
```

remove files 
```{r eval = FALSE}
remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)
```

#### down and up together
```{r}
up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = Description)) +
  #ggplot2::facet_wrap(~ Cluster, scales = "free_y", ncol = 1) +
 # facet_grid(Cluster ~ ., space="free", scales="free") +
  ggforce::facet_col(facets = vars(Cluster), 
                     scales = "free_y", 
                     space = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
  ggtitle(paste0("")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c("#800026FF", "#FD8D3CFF", "gray"),
    guide = "legend",
    limits = c(-22,-3)
  ) +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, hjust = -2.85, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(myPlot, pointSize = 4, textSize = 7, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
up_and_down_enrich_plot <- addSmallLegend(up_and_down_enrich_plot)
up_and_down_enrich_plot


path <- paste0("../../../results/manuscript_figures/Supplemental_LBD_vs_Control_metascape")
saveToPDF(paste0(path, ".pdf"), width = 7, height = 6)
```
### Fold change information 
```{r}
group1_vs_group2 <- read.delim(paste0("../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
up_regulated <- subset(
  group1_vs_group2, adj.P.Val <= 0.05 & logFC > 0.25)
down_regulated <- subset(
  group1_vs_group2, adj.P.Val <= 0.05 & logFC <= -0.25)

# sort by log2FC and adjusted p-val
up_regulated_sort <-
  up_regulated[order(-up_regulated$logFC, up_regulated$adj.P.Val), ]
down_regulated_sort <-
  down_regulated[order(down_regulated$logFC, down_regulated$adj.P.Val), ]

# lock in gene order which is sorted by adjusted p-value
up_regulated_sort$gene_id <-
  factor(up_regulated_sort$gene_id,
         levels = unique(up_regulated_sort$gene_id))
up_regulated_sort$gene_id <-
  fct_rev(up_regulated_sort$gene_id)
down_regulated_sort$gene_id <-
  factor(down_regulated_sort$gene_id,
         levels = unique(down_regulated_sort$gene_id))
down_regulated_sort$gene_id <-
  fct_rev(down_regulated_sort$gene_id)

DEG_df <-
  rbind(up_regulated_sort, down_regulated_sort)
names(DEG_df)[names(DEG_df) == "gene_name"] <- "gene"
```
# Metascape GO summary, genes within term, log2FC
# up
```{r}
up_enrich_df <-
  up_enrich_results_subset[, c("GroupID", "Term", "Description", "Symbols")]
up_enrich_df_melt <- reshape2::melt(up_enrich_df)
up_gene_char <- str_split(up_enrich_df_melt$Symbols, ",")

up_gene_pathway <-
  data.frame(gene = unlist(up_gene_char),
             value = rep(up_enrich_df$Description, lengths(up_gene_char)))
up_pathways_levels <- levels(fct_rev(up_gene_pathway$value))

up_input <- list(
"positive regulation of immune response" = up_gene_char[[1]], 
"positive regulation of cytokine production" = up_gene_char[[2]], 
"cellular response to cytokine stimulus" = up_gene_char[[3]], 
"inflammatory response" = up_gene_char[[4]], 
"cell activation" = up_gene_char[[5]], 
"regulation of cell activation" = up_gene_char[[6]], 
"tube morphogenesis" = up_gene_char[[7]], 
"regulation of kinase activity" = up_gene_char[[8]], 
"negative regulation of cell population proliferation" = up_gene_char[[9]], 
"Hemostasis" = up_gene_char[[10]], 
"positive regulation of cell migration" = up_gene_char[[11]], 
"Malignant pleural mesothelioma" = up_gene_char[[12]], 
"regulation of tumor necrosis factor superfamily cytokine production" = up_gene_char[[13]], 
"enzyme-linked receptor protein signaling pathway" = up_gene_char[[14]], 
"negative regulation of immune system process" = up_gene_char[[15]], 
"VEGFA-VEGFR2 signaling" = up_gene_char[[16]], 
"actin filament-based process" = up_gene_char[[17]], 
"Osteoclast differentiation" = up_gene_char[[18]], 
"TYROBP causal network in microglia" = up_gene_char[[19]], 
"regulation of MAPK cascade" = up_gene_char[[20]]
)
up_data <- fromList(up_input)
up_data$gene <- row.names(up_data)
up_data_melt <- reshape2::melt(up_data)

# get the fold change value for those genes
up_df <- merge(up_data_melt, DEG_df,
                       by = "gene")
# order by fold change 
up_df <- up_df[order(-up_df$logFC, -up_df$adj.P.Val),]
up_df <- subset(up_df, value == "1")
up_df <- as.data.frame(up_df)
# remove columns that aren't needed 
format_up_df <- subset(up_df, select=-c(value, start, end, width, gene_type, AveExpr, t, B))
format_order_up_df <- format_up_df[, c(2,1,4,3,5:9)] # reorder 

# write table 
write.table(format_order_up_df, "Supplemental_LBD_vs_Control_Metascape_upregulated_genes_within_GO.txt", sep= "\t", quote = FALSE, row.names = FALSE)
```
# down
```{r}
down_enrich_df <-
  down_enrich_results_subset[, c("GroupID", "Term", "Description", "Symbols")]
down_enrich_df_melt <- reshape2::melt(down_enrich_df)
down_gene_char <- str_split(down_enrich_df_melt$Symbols, ",")

down_gene_pathway <-
  data.frame(gene = unlist(down_gene_char),
             value = rep(down_enrich_df$Description, lengths(down_gene_char)))
down_pathways_levels <- levels(fct_rev(down_gene_pathway$value))

down_input <- list(
"organic acid catabolic process" = down_gene_char[[1]],
"monocarboxylic acid metabolic process" = down_gene_char[[2]],
"cellular modified amino acid metabolic process" = down_gene_char[[3]],
"NABA MATRISOME ASSOCIATED" = down_gene_char[[4]],
"monocarboxylic acid catabolic process" = down_gene_char[[5]],
"steroid hormone biosynthetic process" = down_gene_char[[6]],
"Valine, leucine and isoleucine degradation" = down_gene_char[[7]],
"Cysteine and methionine metabolism" = down_gene_char[[8]],
"Glycine, serine and threonine metabolism" = down_gene_char[[9]],
"response to toxic substance" = down_gene_char[[10]],
"acyl-CoA metabolic process"  = down_gene_char[[11]],
"Carbon metabolism" = down_gene_char[[12]],
"alcohol metabolic process"  = down_gene_char[[13]],
"Trans-sulfuration, one-carbon metabolism and related pathways" = down_gene_char[[14]],
"estrous cycle" = down_gene_char[[15]],
"microtubule-based movement"  = down_gene_char[[16]],
"Glyoxylate metabolism and glycine degradation" = down_gene_char[[17]],
"tyrosine metabolic process"  = down_gene_char[[18]],
"Biological oxidations" = down_gene_char[[19]],
"carboxylic acid transport" = down_gene_char[[20]]
)
down_data <- fromList(down_input)
down_data$gene <- row.names(down_data)
down_data_melt <- reshape2::melt(down_data)

# get the fold change value for those genes
down_df <- merge(down_data_melt, DEG_df,
                       by = "gene")
# order by fold change 
down_df <- down_df[order(down_df$logFC, -down_df$adj.P.Val),]
down_df <- subset(down_df, value == "1")
down_df <- as.data.frame(down_df)
# remove columns that aren't needed 
format_down_df <- subset(down_df, select=-c(value, start, end, width, gene_type, AveExpr, t, B))
format_order_down_df <- format_down_df[, c(2,1,4,3,5:9)] # reorder 

# write table 
write.table(format_order_down_df, "Supplemental_LBD_vs_Control_Metascape_downregulated_genes_within_GO.txt", sep= "\t", quote = FALSE, row.names = FALSE)
```
# immune
```{r}
GO_immune <-
  subset(
    up_df,
    (
 up_df$variable == "positive regulation of immune response" | 
 up_df$variable == "positive regulation of cytokine production" | 
 up_df$variable == "cellular response to cytokine stimulus" | 
 up_df$variable == "inflammatory response" | 
 up_df$variable == "cell activation" | 
 up_df$variable == "regulation of cell activation" | 
 up_df$variable == "TYROBP causal network in microglia" |  
 up_df$variable == "regulation of tumor necrosis factor superfamily cytokine production" | 
 up_df$variable == "negative regulation of immune system process"
    )
    & up_df$value == 1
  )
GO_immune_unique <- GO_immune[!duplicated(GO_immune[,c('gene')]),]
GO_immune_top <- head(GO_immune_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_immune_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_immune_top$gene_id)
GO_immune_DEG$FC <- 2^(GO_immune_DEG$logFC)
# heatmap 
up_GO_immune_heat <- ggplot(data = GO_immune_DEG, aes(x = gene_type, y = reorder(gene, FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("immune") +
  xlab("LBD/Control")
up_GO_immune_heat
```
# vasculature
```{r}
GO_vasculature <-
  subset(
    up_df,
    (
      up_df$variable == "tube morphogenesis" |
        up_df$variable == "Hemostasis" |
        up_df$variable == "VEGFA-VEGFR2 signaling" |
        up_df$variable == "Osteoclast differentiation"
    )
    & up_df$value == 1
  )
GO_vasculature_unique <- GO_vasculature[!duplicated(GO_vasculature[,c('gene')]),]
GO_vasculature_top <- head(GO_vasculature_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_vasculature_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_vasculature_top$gene_id)
GO_vasculature_DEG$FC <- 2^(GO_vasculature_DEG$logFC)
# heatmap 
up_GO_vasculature_heat <- ggplot(data = GO_vasculature_DEG, aes(x = gene_type, y = reorder(gene, FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("vasculature") +
  xlab("LBD/Control")
up_GO_vasculature_heat
```
# kinase cascade
```{r}
GO_kinase <-
  subset(
    up_df,
    (
 up_df$variable == "regulation of kinase activity" |  
 up_df$variable == "regulation of MAPK cascade"
    )
    & up_df$value == 1
  )
GO_kinase_unique <- GO_kinase[!duplicated(GO_kinase[,c('gene')]),]
GO_kinase_top <- head(GO_kinase_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_kinase_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_kinase_top$gene_id)
GO_kinase_DEG$FC <- 2^(GO_kinase_DEG$logFC)
# heatmap 
up_GO_kinase_heat <- ggplot(data = GO_kinase_DEG, aes(x = gene_type, y = reorder(gene, FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("kinase cascade") +
  xlab("LBD/Control")
up_GO_kinase_heat
```
# organic acid 
```{r}
GO_organic_acid <-
  subset(
    down_df,
    (
 down_df$variable == "organic acid catabolic process" 
    )
    & down_df$value == 1
  )
GO_organic_acid_unique <- GO_organic_acid[!duplicated(GO_organic_acid[,c('gene')]),]
GO_organic_acid_top <- head(GO_organic_acid_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_organic_acid_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_organic_acid_top$gene_id)
GO_organic_acid_DEG$FC <- 2^(abs(GO_organic_acid_DEG$logFC))
GO_organic_acid_DEG$FC <- GO_organic_acid_DEG$FC*-1

# heatmap 
down_GO_organic_acid_heat <- ggplot(data = GO_organic_acid_DEG, aes(x = gene_type, y = reorder(gene, -FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("organic acid catabolic process") +
  xlab("LBD/Control")
down_GO_organic_acid_heat
```
```{r}
GO_steroid <-
  subset(
    down_df,
    (
 down_df$variable == "steroid hormone biosynthetic process" 
    )
    & down_df$value == 1
  )
GO_steroid_unique <- GO_steroid[!duplicated(GO_steroid[,c('gene')]),]
GO_steroid_top <- head(GO_steroid_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_steroid_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_steroid_top$gene_id)
GO_steroid_DEG$FC <- 2^(GO_steroid_DEG$logFC)
GO_steroid_DEG$FC <- GO_steroid_DEG$FC*-1

# heatmap 
down_GO_steroid_heat <- ggplot(data = GO_steroid_DEG, aes(x = gene_type, y = reorder(gene, -FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("steroid") +
  xlab("LBD/Control")
down_GO_steroid_heat
```

# steroid
```{r}
GO_steroid <-
  subset(
    down_df,
    (
 down_df$variable == "steroid hormone biosynthetic process" 
    )
    & down_df$value == 1
  )
GO_steroid_unique <- GO_steroid[!duplicated(GO_steroid[,c('gene')]),]
GO_steroid_top <- head(GO_steroid_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_steroid_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_steroid_top$gene_id)
GO_steroid_DEG$FC <- 2^(abs(GO_steroid_DEG$logFC))
GO_steroid_DEG$FC <- GO_steroid_DEG$FC*-1

# heatmap 
down_GO_steroid_heat <- ggplot(data = GO_steroid_DEG, aes(x = gene_type, y = reorder(gene, -FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = "black", size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("steroid") +
  xlab("LBD/Control")
down_GO_steroid_heat
```
# response to toxic substance
```{r}
GO_toxic <-
  subset(
    down_df,
    (
 down_df$variable == "response to toxic substance" 
    )
    & down_df$value == 1
  )
GO_toxic_unique <- GO_toxic[!duplicated(GO_toxic[,c('gene')]),]
GO_toxic_top <- head(GO_toxic_unique, 40)

# lock in gene order which is sorted by adjusted p-value
GO_toxic_DEG <- subset(DEG_df, DEG_df$gene_id %in% GO_toxic_top$gene_id)
GO_toxic_DEG$FC <- 2^(abs(GO_toxic_DEG$logFC))
GO_toxic_DEG$FC <- GO_toxic_DEG$FC*-1

GO_toxic_DEG$colorVal <-  ifelse(GO_toxic_DEG$FC < -2, 'white', "black")

# heatmap 
down_GO_toxic_heat <- ggplot(data = GO_toxic_DEG, aes(x = gene_type, y = reorder(gene, -FC))) +
  geom_tile(aes(fill = FC), color = "gray") +
  geom_text(aes(label = sprintf("%0.2f", round(FC, digits = 2))), color = GO_toxic_DEG$colorVal, size = 2.75) +
  scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1)) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() +
  theme(
    strip.text = element_text(size = 8),
    legend.position = "none",
    panel.border = element_blank(),
    panel.background = element_blank(),
    plot.margin = margin(0.1, 1, 0.2, 1, "cm"), #t,r,b,l
    panel.spacing = unit(0,'lines'), 
    plot.title = element_text(size = 8, vjust = -1, hjust = 0),
    axis.title.x=element_text(size = 7),
    axis.text.x = element_blank(), 
    axis.ticks.x=element_blank(), 
    axis.title.y = element_blank(), 
    axis.text.y = element_text(size = 7, margin = margin(r = -2)),
    axis.ticks.y=element_blank(),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank())+
    ggtitle("response to toxic substance") +
  xlab("LBD/Control")
down_GO_toxic_heat
```
### legend only
```{r}
u=seq(-2.8,2.1, by=0.01)
df <- data.frame(u)
# heatmap 
legend_data <- ggplot(data = df, aes(x=u,y=row_number(df))) +
  geom_tile(aes(fill = u)) +
    scale_fill_gradientn(colours = c("blue","#FFFFCC","red"), 
                         values = rescale(c(-2.8,0,2.1)),
                         guide = "colorbar", limits=c(-2.8, 2.1),
                         breaks = c(-2.8, 0, 2.1),
                         labels = c(-2.8, 0, 2.1),
                         name = "Fold change
                         ") +
  theme(
    legend.position = "bottom", 
    legend.text = element_text(size =6), 
    legend.title = element_text (size = 8), 
    legend.margin=margin(0,0,1,0),
    legend.key.size = unit(0.5, "cm"))
legend_data <- addSmallLegend(legend_data)

leg <- get_legend(legend_data)
# Convert to a ggplot and print
legend_heat_bar <- as_ggplot(leg)
legend_heat_bar
```
# Combined plot
```{r}
row1 <-
  ggarrange(
    NULL,
    legend_heat_bar,
    NULL,
    NULL,
    ncol = 4,
    labels = c("up-regulated", "", "", ""),
    font.label = list(size = 7, color = "red")
  )

row2 <- ggarrange(
  up_GO_immune_heat,
  up_GO_vasculature_heat,
  up_GO_kinase_heat,
  ncol = 3,
  labels = c("a)", "b)", "c)"),
  font.label = list(size = 8)
  )

row3 <-
  ggarrange(
    NULL,
    NULL,
    NULL,
    NULL,
    ncol = 4,
    labels = c("down-regulated", "", "", ""),
    font.label = list(size = 7, color = "blue")
  )

row4 <- ggarrange(
  down_GO_organic_acid_heat,
  down_GO_steroid_heat,
  down_GO_toxic_heat,
  ncol = 3,
  labels = c("d)", "e)", "f)"),
  font.label = list(size = 8)
  )

combind <-
  ggarrange(
    row1,
    row2,
    row3,
    row4,
    nrow = 4,
    heights = c(0.1, 1, 0.05, 1)
  )
combind

path <- paste0("../../../results/manuscript_figures/Supplemental_Figure_LBD_vs_Control_metascape_gene_FC_heatmaps")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 11)
```
```{r}
```
