---
title: "Figure 2. LBD comparisons"
author: "Kimberly Olney"
date: "08/24/2023"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
library("readxl")
#source(here::here("scripts/R", "gtf_path.R"))
condition <- c("TYPE")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../../../rObjects/dge.filtered.norm.rds"))
```
# Binary list shared gene function
```{r}
fromList <- function (input) {
  # Same as original fromList()...
  elements <- unique(unlist(input))
  data <- unlist(lapply(input, function(x) {
      x <- as.vector(match(elements, x))
      }))
  data[is.na(data)] <- as.integer(0)
  data[data != 0] <- as.integer(1)
  data <- data.frame(matrix(data, ncol = length(input), byrow = F))
  data <- data[which(rowSums(data) != 0), ]
  names(data) <- names(input)
  # ... Except now it conserves your original value names!
  row.names(data) <- elements
  return(data)
  }
```

# DLBD vs TLBD volcano
```{r DLBDvsTLBD}
i <- "DLBDvsTLBD"
tool <- "star_LBD_sub_type"
condition <- c("LBD.type.")
group1_vs_group2 <- read.delim(paste0("../../../../results/", tool, "/DEGs/", condition, "_", i, "_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:4,]
    upFold <- subset(up, logFC > .45)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:3,]
    downFold <- subset(down, logFC < -.75)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("vs", " vs ", i)
DLBDvsTLBD_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
      scale_color_manual(values = my_colors) +
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      #theme(plot.title = element_text(size = 7, margin = margin(0,0,0,0))) +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i)) +
  scale_x_continuous(limits = c(-1, 1), breaks = seq(-1, 1, .5)) +
  scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, 1))

DLBDvsTLBD_volcano
i <- gsub(" vs ", "vs", i)
```

# DLBD vs TLBD metascape 
```{r DLBDvsTLBD_metascape}
# read in enrichment analysis results
i <- c("DLBD_vs_TLBD")
up_enrich_results <-
  read_excel(
    paste0(
      "../../../../results/",
      tool,
      "/metascape/",
      i,
      "_up/metascape_result.xlsx"
    ), sheet = 2
  )

down_enrich_results <-
  read_excel(
    paste0(
      "../../../../results/",
      tool,
      "/metascape/",
      i,
      "_down/metascape_result.xlsx"
    ), sheet = 2
  )

# select the GO term IDs we want to show in the plot
GO_ID_up <-
  c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
  )
GO_ID_down <- c(
    "1_Summary",
    "2_Summary",
    "3_Summary",
    "4_Summary",
    "5_Summary",
    "6_Summary",
    "7_Summary",
    "8_Summary",
    "9_Summary", 
    "10_Summary",
    "11_Summary",
    "12_Summary",
    "13_Summary",
    "14_Summary",
    "15_Summary",
    "16_Summary",
    "17_Summary",
    "18_Summary",
    "19_Summary", 
    "20_Summary"
)

up_enrich_results_subset <-
  up_enrich_results[up_enrich_results$GroupID %in% GO_ID_up, ]
up_enrich_results_subset$Cluster <- c("up-regulated")
up_enrich_results_subset$Description <-
  factor(up_enrich_results_subset$Description,
         levels = up_enrich_results_subset$Description)
up_enrich_results_subset$Description <-
  fct_rev(up_enrich_results_subset$Description)

down_enrich_results_subset <-
  down_enrich_results[down_enrich_results$GroupID %in% GO_ID_down, ]
down_enrich_results_subset$Cluster <- c("down-regulated")
down_enrich_results_subset$Description <-
  factor(down_enrich_results_subset$Description,
         levels = down_enrich_results_subset$Description)
down_enrich_results_subset$Description <-
  fct_rev(down_enrich_results_subset$Description)

# get the number of genes in each summary
up_gene_count <-
  strsplit(as.character(up_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
up_gene_count_df <-
  data.frame(matrix(
    unlist(up_gene_count),
    nrow = length(up_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
up_enrich_results_subset$InTerm <- as.numeric(up_gene_count_df$X1)

down_gene_count <-
  strsplit(as.character(down_enrich_results_subset$InTerm_InList),
           "/",
           fixed = T)
down_gene_count_df <-
  data.frame(matrix(
    unlist(down_gene_count),
    nrow = length(down_gene_count),
    byrow = TRUE
  ), stringsAsFactors = FALSE)
down_enrich_results_subset$InTerm <- as.numeric(down_gene_count_df$X1)

# combine together
up_and_down_enrich_results_subset <- rbind(up_enrich_results_subset, down_enrich_results_subset)

up_and_down_enrich_results_subset$Description <-
      gsub(
       "negative regulation of cellular component organization",
        "negative reg of cellular component organization",
        up_and_down_enrich_results_subset$Description
      )
up_and_down_enrich_results_subset$Description <-
      gsub(
       "positive regulation of cytosolic calcium ion concentration",
        "positive reg of cytosolic calcium ion concentration",
        up_and_down_enrich_results_subset$Description
      )
up_and_down_enrich_results_subset$Description <-
  factor(up_and_down_enrich_results_subset$Description, levels = unique(up_and_down_enrich_results_subset$Description)) 

up_and_down_enrich_results_subset$Description <- fct_rev(up_and_down_enrich_results_subset$Description)
up_and_down_enrich_results_subset$Cluster <- factor(up_and_down_enrich_results_subset$Cluster, levels = c("up-regulated", "down-regulated"))

remove(
  down_enrich_results,
  down_gene_count,
  down_gene_count_df,
  up_enrich_results,
  up_gene_count,
  up_gene_count_df
)

DLBDvsTLBD_up_and_down_enrich_plot <-
  ggplot(data = up_and_down_enrich_results_subset, aes(x = InTerm, y = Description)) +
  #ggplot2::facet_wrap(~ Cluster, scales = "free_y", ncol = 1) +
 # facet_grid(Cluster ~ ., space="free", scales="free") +
  ggforce::facet_col(facets = vars(Cluster), 
                     scales = "free_y", 
                     space = "free") +
  geom_bar(stat = "identity", aes(fill = LogP), width = .7, position = position_dodge(width = .2)) +
  theme_bw() +
  ggtitle(paste0("")) +
  labs(x = "Gene count", y = NULL) +
  guides(fill = guide_legend(title = expression(log[10] ~ "(" ~ italic("p") ~ "-value)"))) +
  scale_fill_gradientn(
    colours = c("#800026FF", "#FD8D3CFF", "gray"),
    guide = "legend",
    limits = c(-13,-1)
  ) +
    theme(strip.text = element_text(size = 8), 
          axis.text.y = element_text(size = 8),
          axis.text.x = element_text(size = 8), 
          axis.title.x = element_text(size = 8), 
          legend.text = element_text(size = 8),
          legend.title = element_text(size = 8),
          legend.margin=margin(0,0.5,0,0),
          legend.box.margin=margin(-10,-2,-10,-7.5), 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
          plot.title = element_text(size = 8, hjust = -3.25, vjust=0, margin = margin(0,0,0,0)))
 #  theme(aspect.ratio = 1.5) # to reduce the size of the boxes 
addSmallLegend <- function(myPlot, pointSize = 4, textSize = 7, spaceLegend = .5) {
    myPlot +
        guides(shape = guide_legend(override.aes = list(size = pointSize)),
               color = guide_legend(override.aes = list(size = pointSize))) +
        theme(legend.title = element_text(size = textSize), 
              legend.text  = element_text(size = textSize),
              legend.key.size = unit(spaceLegend, "lines"))
}

# Apply on original plot
DLBDvsTLBD_up_and_down_enrich_plot <- addSmallLegend(DLBDvsTLBD_up_and_down_enrich_plot)
DLBDvsTLBD_up_and_down_enrich_plot
```
# Combine all plots 
```{r}
combind <- ggarrange(
  DLBDvsTLBD_volcano,
  DLBDvsTLBD_up_and_down_enrich_plot,
  labels = c("a)", "b)"), 
  widths = c(2.5, 4.25), 
  font.label = list(size = 8)
  )
combind

path <- paste0("../../../../results/manuscript_figures/Supplemental_Figure_DLBD_vs_TLBD")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 4.5)
```
# Supplemental
## LBD Tau vs LBD no Tau volcano
```{r LBD_Braak}
group1_vs_group2 <- read.delim(paste0("../../../../results/star_LBD_sub_type/DEGs/LBD.type.Braak_LBD_BraakvsLBD_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }

group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
data <- group1_vs_group2

upFold <- subset(data, logFC > .30)
downFold <- subset(data, logFC < -.35)
almost_sig <- subset(data, P.Value < .001)
SERPINA5 <- subset(data, gene_name == "SERPINA5")


LBD_Tau_vs_LBD_NoTau_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
      scale_color_manual(values = "gray") + #
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle("LBD Tau+ vs LBD Tau-") +
  scale_x_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, .5)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, 1))
LBD_Tau_vs_LBD_NoTau_volcano
```

## DLBD Tau vs DLBD no Tau volcano
```{r DLBD_Braak}
group1_vs_group2 <- read.delim(paste0("../../../../results/star_LBD_sub_type_Braak/DEGs/LBD.type.Braak_DLBD_BraakvsDLBD_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }

group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
data <- group1_vs_group2

upFold <- subset(data, logFC > .30)
downFold <- subset(data, logFC < -.35)
almost_sig <- subset(data, P.Value < .001)
SERPINA5 <- subset(data, gene_name == "SERPINA5")


DLBD_Tau_vs_DLBD_NoTau_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
      scale_color_manual(values = "gray") + #
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle("DLBD Tau+ vs DLBD Tau-") +
  scale_x_continuous(limits = c(-1.5, 1.5), breaks = seq(-1.5, 1.5, .5)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, 1))
DLBD_Tau_vs_DLBD_NoTau_volcano
```

## DLBD APOE E4+ vs DLBD APOE E4- volcano
```{r DLBDvsTLBD}
group1_vs_group2 <- read.delim(paste0("../../../../results/star_LBD_sub_type/DEGs/LBD.type_APOE._DLBD_E4vsDLBD_gene_DEGs_FDRq1.00.txt"))
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }

group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
data <- group1_vs_group2

upFold <- subset(data, logFC > .30)
downFold <- subset(data, logFC < -.35)
almost_sig <- subset(data, P.Value < .001)
SERPINA5 <- subset(data, gene_name == "SERPINA5")


DLBD_E4_vs_DLBD_volcano <- ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
      scale_color_manual(values = "gray") + #
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle("DLBD APOE E4+ vs DLBD APOE E4-") +
  scale_x_continuous(limits = c(-1, 1), breaks = seq(-1, 1, .5)) +
  scale_y_continuous(limits = c(0, 5), breaks = seq(0, 5, 1))
DLBD_E4_vs_DLBD_volcano
```
# Within DLBD supplemental plots
```{r}
withinDLBD <- ggarrange(
  LBD_Tau_vs_LBD_NoTau_volcano,
  DLBD_Tau_vs_DLBD_NoTau_volcano,
  DLBD_E4_vs_DLBD_volcano,
  ncol = 2,
  nrow = 2, 
  labels = c("a)","b)", "c)"), 
  font.label = list(size = 8)
)
withinDLBD
path <- paste0("../../../../results/manuscript_figures/Supplemental_LBD_and_DLBD_Braak_DE")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 8)

```

