---
title: "Supplemental Figure. RIN and alignment metrics"
output: html_document
date: "2023-09-03"
---

# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# Read in data
```{r}
source(here::here("scripts/R", "file_paths_and_colours.R"))
cell_biomarker_lcpm <- read.delim("../../../../rObjects/gene_tables/cell_biomarker_cpm.txt", sep = "\t")
metadata <- merge(metadata, cell_biomarker_lcpm, by = "NPID")
```
# Violin plots
RIN
ENO2
coding
intronic
intergenic
```{r message=FALSE, warning=FALSE, tidy=TRUE}
metadata_continuous <-
  data.frame(
    metadata$RIN,
    metadata$PCT_CODING_BASES,
    metadata$PCT_INTRONIC_BASES,
    metadata$PCT_INTERGENIC_BASES,
    metadata$ENO2
  )
column_variables <-
  c(
    "RIN",
    "% coding bases",
    "% intronic",
    "% intergenic", 
    "ENO2"
  )


violin_plot_fun <- function(i, j) {
  ggplot(metadata, aes(TYPE, i, fill = TYPE)) +
    geom_violin(alpha = 0.5) +
    geom_boxplot(width = 0.1, outlier.shape = NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), 
                alpha = 0.2, size = .5) +
    theme_bw() + 
    theme(
    plot.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    strip.text = element_text(size = 8), 
    axis.text.y = element_text(size = 8),
    axis.title.y = element_text(size = 8),
    axis.title.x = element_blank(),
    plot.margin = margin(0.1, 0.5, 0.8, 0.5, "cm")) + #t,r,b,l
    ggtitle(j) +
    ylab(j) +
    stat_compare_means(size = 2.5) +
    scale_fill_manual(values=TypeColors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, i = metadata_continuous, j = column_variables)
violin_plots
```


```{r}
combind <-
  ggarrange(plotlist = violin_plots,
    nrow = 3,
    ncol = 2,
    labels = c("a)", "b)", "c)", "d)", "e)"), 
    font.label = list(size = 8)
    )
combind

path <- paste0("../../../../results/manuscript_figures/Supplemental_RIN_alignment")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 9)
```

```{r message=FALSE, warning=FALSE, tidy=TRUE}
metadata_continuous <-
  data.frame(
    metadata$RIN,
    metadata$PCT_CODING_BASES,
    metadata$PCT_INTRONIC_BASES,
    metadata$PCT_INTERGENIC_BASES, 
    metadata$ENO2
  )
column_variables <-
  c(
    "RIN",
    "% coding bases",
    "% intronic",
    "% intergenic",
    "ENO2"
  )

violin_plot_fun <- function(i, j) {
  ggplot(metadata, aes(TYPE, i, fill = TYPE)) +
    geom_violin(alpha = 0.5) +
    geom_boxplot(width = 0.1, outlier.shape = NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), 
                alpha = 0.2, size = .5) +
    theme_bw() + 
    theme(
    plot.title = element_text(size = 8),
    axis.text.x = element_text(size = 8),
    strip.text = element_text(size = 8), 
    axis.text.y = element_text(size = 8),
    axis.title.y = element_text(size = 8),
    axis.title.x = element_blank(),
    plot.margin = margin(0.1, 0.5, 0.8, 0.5, "cm")) + #t,r,b,l
    ggtitle(j) +
    ylab(j) +
    stat_compare_means(size = 2.5) +
    scale_fill_manual(values=TypeColors) +
    theme(legend.position = "none")  +
    facet_grid(. ~ sex_inferred)
}
violin_plots_sex <-
  Map(violin_plot_fun, i = metadata_continuous, j = column_variables)
violin_plots_sex
```

```{r}
combind <-
  ggarrange(plotlist = violin_plots_sex,
    nrow = 3,
    ncol = 2,
    labels = c("a)", "b)", "c)", "d)", "e)"), 
    font.label = list(size = 8)
    )
combind

path <- paste0("../../../../results/manuscript_figures/Supplemental_RIN_alignment_sex")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 9)
```
```{r}
```