---
title: "Brain in A Blender - updating cell type table and functions "
author: "Kimberly Olney"
date: "4/9/2023"
output: html_document
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# load BinB cell type master table 
note, the table was obtained by cloning the BinB git repo first
git clone https://github.com/hagenaue/BrainInABlender.git
```{r set_variables, warning=FALSE}
load("/research/labs/neurology/fryer/m239830/tools/BrainInABlender/data/CellTypeSpecificGenes_Master3.rda")
```
# remove TTR, FOLR1, and PRLR from table
these will be choroid plexus markers that we will add to the table 
```{r}
# remove rows with NA
df <- na.omit(CellTypeSpecificGenes_Master3)
# remove choroid plexus markers 
df <- subset(df, !(df$GeneSymbol_Human %in% c("TTR", "PRLR", "FOLR1")))
```
# add choroid plexus markers
```{r}
# read in choroid plexus gene table, 
# see Olney et al. 2022 for details about choroid plexus markers and contamination 
choroid <- read.delim("/research/labs/neurology/fryer/m239830/LBD_CWOW/scripts/cell_type_inference/BrainInABlender/choroid_Olney2022.tsv", header = FALSE)
# add colnames to choroid data frame using the df columns 
colnames(choroid) <- colnames(df)
# add to choroid to df to update the cell type table 
CellTypeSpecificGenes_Master3 <- rbind(df, choroid)
# save **note this will overwrite the orginal CellType file
save(CellTypeSpecificGenes_Master3, file = "/research/labs/neurology/fryer/m239830/tools/BrainInABlender/data/CellTypeSpecificGenes_Master3.rda")
```


