---
title: "Examine clinical stats"
author: "Kimberly Olney, Ph.D"
date: "10/07/2022"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

# Setup
```{r setup}
# Also do Session > Set Working Directory > Choose Directory
knitr::opts_knit$set(root.dir = ".")
```
# libraries
```{r}
library(gtools)
library(tidyr)
library(wesanderson) # colors
```
# User defined variables
```{r set_variables}
pathToRef = c("/research/labs/neurology/fryer/projects/references/human/")
pathToRawData = c("/research/labs/neurology/fryer/projects/LBD_CWOW/")

# color theme
TypeColors <- c("#4682B4", "#B4464B","#B4AF46", "gray35")
SexColors <- c("orange", "blue")
```

# Read data
```{r read_data}
# read in metadata
metadata <- read.delim(paste0(pathToRawData, "metadata_expanded.tsv"), 
                       header = TRUE,
                       sep = "\t")
# remove technical replicates (i.e lane 1 and lane 2)
metadata <- metadata[!duplicated(metadata[,c('NPID')]),]
# remove samples that don't have RNA data
metadata <- metadata %>% drop_na(flowcell_and_lane)
metadata <- metadata %>%
  mutate(across('AD.subtype', str_replace, 'typical', 'Typical'))
write.table(metadata, paste0(pathToRawData, "RNA_metadata.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
```
# Create bar plots for catrogical variables 
```{r bar_plot, cache=FALSE}
# create bar plot showing number of samples for each end point criteria
df <- data.frame(metadata$TYPE, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "sex inferred") # rename column 
bar_plot <- ggplot(df, aes(`Disease group`, ..count.., fill = `Disease group`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("Disease group") + 
  geom_text(stat='count', aes(label=..count..), vjust=1.6, color="white", size=3.5) + 
  scale_fill_manual(values=TypeColors) 
bar_plot
```
```{r}
data <- df %>% 
  group_by(`Disease group`) %>%
  dplyr::count() %>% 
  ungroup() %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `Disease group`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "Disease group")) +
  scale_fill_manual(values=TypeColors) +
  coord_polar(theta = "y") + 
  theme_void()
```
# side by side sex 
```{r}
ggplot(df, aes(x = `Disease group`, fill = `sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("Disease group ") + 
  geom_text(stat='count', aes(x = `Disease group`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# pie by sex 
```{r}
ggplot(df, aes(x = factor(1), fill = `sex inferred`)) + 
  geom_bar(width = 1,position = "fill") + 
  theme_bw() +
  facet_wrap(~`Disease group`, ncol = 4) +
  scale_fill_manual(values = SexColors) +
  coord_polar(theta="y") +
  theme(
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_blank()
  )
```

```{r}
data <- df %>% 
  group_by(`sex inferred`,`Disease group`) %>%
  dplyr::count() %>% 
  ungroup(`sex inferred`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `sex inferred`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
    facet_wrap(~`Disease group`, ncol = 4) +
  guides(fill = guide_legend(title = "Sex inferred")) +
  scale_fill_manual(values=SexColors) +
  coord_polar(theta = "y") + 
  theme_void()
```
# LBD type 
```{r}
df <- data.frame(metadata$TYPE, metadata$LBD.type, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "LBD type", "Sex inferred") # rename column 

ggplot(df, aes(`Disease group`, ..count.., fill = `LBD type`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("LBD type") + 
  geom_text(stat='count', aes(label=..count..), vjust=1.6, color="white", size=3.5) + 
  scale_fill_manual(values=wes_palette(n=4, name="Rushmore"))

data <- df %>% 
  group_by(`LBD type`) %>%
  dplyr::count() %>% 
  ungroup(`LBD type`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `LBD type`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "LBD type")) +
  scale_fill_manual(values=wes_palette(n=4, name="Rushmore")) +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `LBD type`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("LBD type") + 
  geom_text(stat='count', aes(x = `LBD type`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```


# AD subtype 
```{r}
df <- data.frame(metadata$TYPE, metadata$AD.subtype, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "AD subtype", "Sex inferred") # rename column 

ggplot(df, aes(`Disease group`, ..count.., fill = `AD subtype`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("AD subtype") + 
  geom_text(stat='count', aes(label=..count..), vjust=1.6, color="white", size=3.5) + 
  scale_fill_brewer(palette="BrBG")

data <- df %>% 
  group_by(`AD subtype`) %>%
  dplyr::count() %>% 
  ungroup(`AD subtype`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `AD subtype`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "AD subtype")) +
  scale_fill_brewer(palette="BrBG") +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `AD subtype`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("AD subtype") + 
  geom_text(stat='count', aes(x = `AD subtype`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# APOE
```{r}
df <- data.frame(metadata$TYPE, metadata$APOE, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "APOE", "Sex inferred") # rename column 
df$`APOE` <- as.factor(df$`APOE`)
ggplot(df, aes(`Disease group`, ..count.., fill = `APOE`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("APOE") +
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5), color="white", size=3.5)

data <- df %>% 
  group_by(`APOE`) %>%
  dplyr::count() %>% 
  ungroup(`APOE`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `APOE`)) +
  geom_col(color = "black") +
    geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "APOE")) +
  coord_polar(theta = "y") + 
  theme_void()


ggplot(df, aes(x = `APOE`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("APOE") + 
  geom_text(stat='count', aes(x = `APOE`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```



# CDLB  
```{r}
df <- data.frame(metadata$TYPE, metadata$CDLB, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "CDLB", "Sex inferred") # rename column 

ggplot(df, aes(`Disease group`, ..count.., fill = `CDLB`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("CDLB") + 
  geom_text(stat='count', aes(label=..count..), vjust=1.6, color="white", size=3.5) + 
  scale_fill_brewer(palette="BrBG")

data <- df %>% 
  group_by(`CDLB`) %>%
  dplyr::count() %>% 
  ungroup(`CDLB`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `CDLB`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "CDLB")) +
  scale_fill_brewer(palette="BrBG") +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `CDLB`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("CDLB") + 
  geom_text(stat='count', aes(x = `CDLB`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```

# Braak.NFT  
```{r}
df <- data.frame(metadata$TYPE, metadata$Braak.NFT, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "Braak.NFT", "Sex inferred") # rename column 
df$Braak.NFT <- as.factor(df$Braak.NFT)
ggplot(df, aes(`Disease group`, ..count.., fill = `Braak.NFT`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("Braak.NFT") + 
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust=.5), color="black", size=3.5) + 
  scale_fill_brewer(palette="YlGn")

data <- df %>% 
  group_by(`Braak.NFT`) %>%
  dplyr::count() %>% 
  ungroup(`Braak.NFT`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `Braak.NFT`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("black"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "Braak.NFT")) +
  scale_fill_brewer(palette="YlGn") +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `Braak.NFT`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("Braak.NFT") + 
  geom_text(stat='count', aes(x = `Braak.NFT`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# Thal amyloid
```{r}
df <- data.frame(metadata$TYPE, metadata$Thal.amyloid, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "Thal amyloid", "Sex inferred") # rename column 
df$`Thal amyloid` <- as.factor(df$`Thal amyloid`)
ggplot(df, aes(`Disease group`, ..count.., fill = `Thal amyloid`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("Thal amyloid") + 
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust=.5), color="black", size=3.5) + 
  scale_fill_brewer(palette="YlGn")

data <- df %>% 
  group_by(`Thal amyloid`) %>%
  dplyr::count() %>% 
  ungroup(`Thal amyloid`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `Thal amyloid`)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("black"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "Thal amyloid")) +
  scale_fill_brewer(palette="YlGn") +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `Thal amyloid`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("Thal amyloid") + 
  geom_text(stat='count', aes(x = `Thal amyloid`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# MF SP
```{r}
df <- data.frame(metadata$TYPE, metadata$MF.SP, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "MF SP", "Sex inferred") # rename column 
df$`MF SP` <- as.factor(df$`MF SP`)
ggplot(df, aes(`Disease group`, ..count.., fill = `MF SP`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("MF SP") #+ 

data <- df %>% 
  group_by(`MF SP`) %>%
  dplyr::count() %>% 
  ungroup(`MF SP`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `MF SP`)) +
  geom_col(color = "black") +
  guides(fill = guide_legend(title = "MF SP")) +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `MF SP`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("MF SP") + 
  geom_text(stat='count', aes(x = `MF SP`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# MF NFT
```{r}
df <- data.frame(metadata$TYPE, metadata$MF.NFT, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "MF NFT", "Sex inferred") # rename column 
df$`MF NFT` <- as.factor(df$`MF NFT`)
ggplot(df, aes(`Disease group`, ..count.., fill = `MF NFT`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("MF NFT") #+ 

data <- df %>% 
  group_by(`MF NFT`) %>%
  dplyr::count() %>% 
  ungroup(`MF NFT`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `MF NFT`)) +
  geom_col(color = "black") +
  guides(fill = guide_legend(title = "MF NFT")) +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `MF NFT`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("MF NFT") + 
  geom_text(stat='count', aes(x = `MF NFT`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# MF LB
```{r}
df <- data.frame(metadata$TYPE, metadata$MF.LB, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "MF LB", "Sex inferred") # rename column 
df$`MF LB` <- as.factor(df$`MF LB`)
ggplot(df, aes(`Disease group`, ..count.., fill = `MF LB`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("MF LB") #+ 

data <- df %>% 
  group_by(`MF LB`) %>%
  dplyr::count() %>% 
  ungroup(`MF LB`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `MF LB`)) +
  geom_col(color = "black") +
  guides(fill = guide_legend(title = "MF LB")) +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `MF LB`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("MF LB") + 
  geom_text(stat='count', aes(x = `MF LB`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# Cing LB
```{r}
df <- data.frame(metadata$TYPE, metadata$Cing.LB, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "Cing LB", "Sex inferred") # rename column 
df$`Cing LB` <- as.factor(df$`Cing LB`)
ggplot(df, aes(`Disease group`, ..count.., fill = `Cing LB`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("Cing LB") #+ 

data <- df %>% 
  group_by(`Cing LB`) %>%
  dplyr::count() %>% 
  ungroup(`Cing LB`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `Cing LB`)) +
  geom_col(color = "black") +
  guides(fill = guide_legend(title = "Cing LB")) +
  coord_polar(theta = "y") + 
  theme_void()

ggplot(df, aes(x = `Cing LB`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("Cing LB") + 
  geom_text(stat='count', aes(x = `Cing LB`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# MF Amyloid
```{r}
df <- data.frame(metadata$TYPE, metadata$MF.Amyloid, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "MF Amyloid", "Sex inferred") # rename column 
df$`MF Amyloid` <- as.factor(df$`MF Amyloid`)
ggplot(df, aes(`Disease group`, ..count.., fill = `MF Amyloid`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("MF Amyloid") +
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5), color="white", size=3.5)

data <- df %>% 
  group_by(`MF Amyloid`) %>%
  dplyr::count() %>% 
  ungroup(`MF Amyloid`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `MF Amyloid`)) +
  geom_col(color = "black") +
    geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "MF Amyloid")) +
  coord_polar(theta = "y") + 
  theme_void()


ggplot(df, aes(x = `MF Amyloid`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("MF Amyloid") + 
  geom_text(stat='count', aes(x = `MF Amyloid`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# Cing Synuclein
```{r}
df <- data.frame(metadata$TYPE, metadata$Cing.Synuclein, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "Cing Synuclein", "Sex inferred") # rename column 
df$`Cing Synuclein` <- as.factor(df$`Cing Synuclein`)
ggplot(df, aes(`Disease group`, ..count.., fill = `Cing Synuclein`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("Cing Synuclein") +
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5), color="white", size=3.5)

data <- df %>% 
  group_by(`Cing Synuclein`) %>%
  dplyr::count() %>% 
  ungroup(`Cing Synuclein`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `Cing Synuclein`)) +
  geom_col(color = "black") +
    geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "Cing Synuclein")) +
  coord_polar(theta = "y") + 
  theme_void()


ggplot(df, aes(x = `Cing Synuclein`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("Cing Synuclein") + 
  geom_text(stat='count', aes(x = `Cing Synuclein`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```
# MF Tau
```{r}
df <- data.frame(metadata$TYPE, metadata$MF.Tau, metadata$sex_inferred)# create dataframe of endpoint criteria 
colnames(df) <- c("Disease group", "MF Tau", "Sex inferred") # rename column 
df$`MF Tau` <- as.factor(df$`MF Tau`)
ggplot(df, aes(`Disease group`, ..count.., fill = `MF Tau`)) + 
  geom_bar() +
  theme_bw() + 
  ggtitle("MF Tau") +
  geom_text(stat='count', aes(label=..count..), position = position_stack(vjust = 0.5), color="white", size=3.5)

data <- df %>% 
  group_by(`MF Tau`) %>%
  dplyr::count() %>% 
  ungroup(`MF Tau`) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(data, aes(x = "", y = perc, fill = `MF Tau`)) +
  geom_col(color = "black") +
    geom_label(aes(label = labels), color = c("white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "MF Tau")) +
  coord_polar(theta = "y") + 
  theme_void()


ggplot(df, aes(x = `MF Tau`, fill = `Sex inferred`)) + 
  geom_bar(aes(y = ..count..), position = "dodge") + 
  theme_bw() + 
  ggtitle("MF Tau") + 
  geom_text(stat='count', aes(x = `MF Tau`, label=..count..), 
            position = position_dodge(width = 1), 
              vjust=1.25, color="white", size=3.5) + 
  scale_fill_manual(values = SexColors)
```


```{r}
pheno_df <- data.frame(metadata$weight_kg, metadata$dose_ml_per_hr, metadata$duration_min, metadata$start_heart_rate, metadata$end_heart_rate, metadata$start_temp, metadata$end_temp, metadata$start_MAP, metadata$end_MAP, metadata$age_days)
c_pheno_df <- colnames(df)
labels <-
  c(
    "Weight (kg)",
    "Dose mL per hour",
    "Mins from injection till sacrifice", 
    "Initial heart rate", 
    "Final heart rate", 
    "Initial body temperature",
    "Final body temperature", 
    "Initial MAP", 
    "Final  MAP", 
    "Days old" 
  )
vio_Func_ttest <- function(j, i, k) {
  ggplot(metadata, aes(x = group, y = i, color = group)) + ylab(j)  +
    geom_violin() + scale_color_manual(values = c("black", "purple")) +
    geom_boxplot(width = 0.1, outlier.size = -1, outlier.shape = NA) + 
    stat_compare_means(method = "t.test", size = 4, label.x = 1.25) +
    geom_sina(aes(shape = factor(group)),
                size = 3) +
    theme(legend.position = "none") + ggtitle(k) + ylab(k) + scale_shape_manual(
      values = c(14, 10)) +
    theme(
      axis.title.x = element_text(size = 12),
      axis.text.x =
        element_text(size = 12)
    ) +
    theme(
      axis.title.y = element_text(size = 12),
      axis.text.y =
        element_text(size = 12) 
    ) +
    theme(
      title = element_text(size = 12)
    )
}
all_plots <- Map(vio_Func_ttest, i = pheno_df, j = c_pheno_df, k = labels)
all_plots
plotnames = imap(all_plots, ~paste0("", .y, "_ttest.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, all_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 4, width = 4))
```