---
title: "Differential expression in CWOW samples"
author: "Kimberly Olney, Ph.D."
date: "09/30/2022"
output:
  html_document:
    df_print: paged
  pdf_document: default
params:
  args: myarg
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
source(here::here("scripts/R", "gtf_path.R"))
condition <- c("ATS")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../rObjects/dge.filtered.norm.rds"))
```
# Design
```{r design}
design <-
  model.matrix(~ 0 + 
      ATS_names + 
      sex_inferred + 
      flowcell_and_lane + 
      Oligodendrocyte.Zscore +
      Neuron_Interneuron.Zscore + 
      Neuron_Projection.Zscore +
      Mural.Zscore +
      Astrocyte.Zscore +
      PCT_INTRONIC_BASES,
    dge.filtered.norm$samples
  )

colnames(design) <-
  c(
    "no_pathology",
    "amyloid",
    "amyloid_tau",
    "pure_synuclein",
    "low_amyloid_synuclein",
    "high_amyloid_synuclein",
    "amyloid_synuclein_tau",
    "sex",
    "Batch1",
    "Batch2",
    "Batch3",
    "Batch4",
    "Batch5",
    "Batch6",
    "Batch7",
    "Oligodendrocyte.Zscore",
    "Neuron_Interneuron.Zscore",
    "Neuron_Projection.Zscore",
    "Mural.Zscore", 
    "Astrocyte.Zscore", 
    "PCT_INTRONIC_BASES"
  )
```
# Contrast
```{r contrast}
contrasts <- makeContrasts(
  amyloid_vs_no_pathology =  amyloid - no_pathology,
  amyloid_tau_vs_no_pathology = amyloid_tau - no_pathology,
  low_amyloid_synuclein_vs_no_pathology = low_amyloid_synuclein - no_pathology,
  high_amyloid_synuclein_vs_no_pathology = high_amyloid_synuclein - no_pathology,
  amyloid_synuclein_tau_vs_no_pathology = amyloid_synuclein_tau - no_pathology,
 
  amyloid_tau_vs_amyloid = amyloid_tau - amyloid,
  low_amyloid_synuclein_vs_amyloid = low_amyloid_synuclein - amyloid,
  high_amyloid_synuclein_vs_amyloid = high_amyloid_synuclein - amyloid,
  amyloid_synuclein_tau_vs_amyloid = amyloid_synuclein_tau - amyloid,

  low_amyloid_synuclein_vs_amyloid_tau = low_amyloid_synuclein - amyloid_tau,
  high_amyloid_synuclein_vs_amyloid_tau = high_amyloid_synuclein - amyloid_tau,
  amyloid_synuclein_tau_vs_amyloid_tau = amyloid_synuclein_tau - amyloid_tau,
  
  high_amyloid_synuclein_vs_low_amyloid_synuclein = high_amyloid_synuclein - low_amyloid_synuclein,
  amyloid_synuclein_tau_vs_low_amyloid_synuclein = amyloid_synuclein_tau - low_amyloid_synuclein,
  
  amyloid_synuclein_tau_vs_high_amyloid_synuclein = amyloid_synuclein_tau - high_amyloid_synuclein,

  levels = colnames(design))
allComparisons <- colnames(contrasts)
```

# Volcano plots
```{r volcano, warning=FALSE}
for (i in allComparisons) {
  group1_vs_group2 <-
    read.delim(
      paste0(
        "../../results/",
        tool,
        "/DEGs/",
        condition,
        "_",
        i,
        "_gene_DEGs_FDRq1.00.txt"
      )
    )
  color_values <- vector()
  max <- nrow(group1_vs_group2)
  for (row in 1:max) {
    if (group1_vs_group2$adj.P.Val[row] < 0.05) {
      if (group1_vs_group2$logFC [row] > 0.25) {
        color_values <- c(color_values, 1)
      }
      else if (group1_vs_group2$logFC[row] < -.25) {
        color_values <- c(color_values, 2)
      }
      else {
        color_values <- c(color_values, 3)
      }
    }
    else{
      color_values <- c(color_values, 3)
    }
  }
  group1_vs_group2$color_adjpval_0.05 <- factor(color_values)
  data <- group1_vs_group2
  # plot only if there are DEGs with p_val_adj < 0.05
  num <- subset(data, (adj.P.Val < 0.05 & logFC < -.25)  | (adj.P.Val < 0.05 & logFC > .25 ))
  num <- nrow(num)
  if (num != 0) {
    up <- data[data$color_adjpval_0.05 == 1,]
    up10 <- up[1:10,]
    upFold <- subset(up, logFC > 1)
    upFold <- upFold[!(upFold$gene_name %in% up10$gene_name),]
    down <- data[data$color_adjpval_0.05 == 2,]
    down10 <- down[1:10,]
    downFold <- subset(down, logFC < -1)
    downFold <- downFold[!(downFold$gene_name %in% down10$gene_name),]
    if (!1 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("blue", "gray")
    } else if (!2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("red", "gray")
    } else if (!1 %in% unique(data$color_adjpval_0.05) &&
               !2 %in% unique(data$color_adjpval_0.05)) {
      my_colors <- c("gray")
    } else {
      my_colors <- c("red", "blue", "gray")
    }
    hadjpval <- (-log10(max(data$P.Value[data$adj.P.Val < 0.05],
                            na.rm = TRUE)))
    negFC <- c(-.25)
    posFC <- c(.25) 
    i <- gsub("_", " ", i)
    p <-
      ggplot(data = data,
             aes(
               x = logFC,
               y = -log10(P.Value),
               color = color_adjpval_0.05
             )) +
      geom_point(alpha = 0.8, size = 1) +
      theme_bw() +
      theme(legend.position = "none") +
      scale_color_manual(values = my_colors) +
      labs(
        title = "",
        x = expression(log[2](FC)),
        y = expression(-log[10] ~ "(" ~ italic("p") ~ "-value)")
      )  +
      geom_hline(yintercept = hadjpval,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = negFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      geom_vline(xintercept = posFC,
                 #  horizontal line
                 colour = "#000000",
                 linetype = "dashed") +
      ggtitle(paste0(i)) +
      geom_text_repel(
        data = up10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 3,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) +
      geom_text_repel(
        data = upFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "maroon",
        fontface = "italic",
        size = 3,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) +
      geom_text_repel(
        data = down10,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 3,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      ) +
      geom_text_repel(
        data = downFold,
        aes(
          x = logFC,
          y = -log10(P.Value),
          label = gene_name
        ),
        color = "navyblue",
        fontface = "italic",
        size = 3,
        max.overlaps = getOption("ggrepel.max.overlaps", default = 10)
      )
    p
    i <- gsub(" ", "_", i)
    # save
    path <-
      paste0(
        "../../results/",
        tool,
        "/volcano/",
        condition,
        "_",
        i,
        "_gene_volcano_FDRq0.05"
      )
    pdf(paste0(path, ".pdf"),
        height = 5,
        width = 5)
    print(p)
    dev.off()
    
    print(paste("i =", i))
  }
} 
```
```{r cleanup}
# clean up
remove(up, up10, upFold, group1_vs_group2, downFold, down10, data, df, p)
```
# Make excel table
```{r excel}
# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/DEGs/", condition, "_", i,
    "_gene_DEGs_FDRq1.00.txt"
  )
  assign(paste0(i),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
}

list_of_datasets <- list(
"A_vs_NP" = amyloid_vs_no_pathology,
"AT_vs_NP" = amyloid_tau_vs_no_pathology,     
"lowAS_vs_NP" = low_amyloid_synuclein_vs_no_pathology,
"highAS_vs_NP" = high_amyloid_synuclein_vs_no_pathology,         
"AST_vs_NP" = amyloid_synuclein_tau_vs_no_pathology,
"AT_vs_A "= amyloid_tau_vs_amyloid,
"lowAS_vs_A" = low_amyloid_synuclein_vs_amyloid,
"highAS_vs_A" = high_amyloid_synuclein_vs_amyloid, 
"AST_vs_A" = amyloid_synuclein_tau_vs_amyloid,
"lowAS_vs_AT" = low_amyloid_synuclein_vs_amyloid_tau,
"highAS_vs_AT"= high_amyloid_synuclein_vs_amyloid_tau,
"AST_vs_AT"= amyloid_synuclein_tau_vs_amyloid_tau,
"hightAS_vs_lowAS"= high_amyloid_synuclein_vs_low_amyloid_synuclein, 
"AST_vs_lowAS"= amyloid_synuclein_tau_vs_low_amyloid_synuclein, 
"AST_vs_highAS"= amyloid_synuclein_tau_vs_high_amyloid_synuclein)
write.xlsx(list_of_datasets, file = paste0(
    "../../results/",
    tool,
    "/DEGs/", condition,".DEGs.FDRq1.00.xlsx"))
```
clean up
```{r cleanup_excel}
remove(
amyloid_vs_no_pathology,
amyloid_tau_vs_no_pathology,     
low_amyloid_synuclein_vs_no_pathology,
high_amyloid_synuclein_vs_no_pathology,         
amyloid_synuclein_tau_vs_no_pathology,
amyloid_tau_vs_amyloid,
low_amyloid_synuclein_vs_amyloid,
high_amyloid_synuclein_vs_amyloid, 
amyloid_synuclein_tau_vs_amyloid,
low_amyloid_synuclein_vs_amyloid_tau,
high_amyloid_synuclein_vs_amyloid_tau,
amyloid_synuclein_tau_vs_amyloid_tau,
high_amyloid_synuclein_vs_low_amyloid_synuclein, 
amyloid_synuclein_tau_vs_low_amyloid_synuclein, 
amyloid_synuclein_tau_vs_high_amyloid_synuclein
)
```
# Excel table of significant DEGs
```{r}
# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/DEGs/", condition, "_", i,
    "_gene_DEGs_FDRq0.05_logFC_0.25.txt"
  )
  assign(paste0(i),
         tryCatch(
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ), error=function(e) NULL))
}

list_of_datasets <- list(
"A_vs_NP" = amyloid_vs_no_pathology,
"AT_vs_NP" = amyloid_tau_vs_no_pathology,     
"lowAS_vs_NP" = low_amyloid_synuclein_vs_no_pathology,
"highAS_vs_NP" = high_amyloid_synuclein_vs_no_pathology,         
"AST_vs_NP" = amyloid_synuclein_tau_vs_no_pathology,
"AT_vs_A "= amyloid_tau_vs_amyloid,
"lowAS_vs_A" = low_amyloid_synuclein_vs_amyloid,
"highAS_vs_A" = high_amyloid_synuclein_vs_amyloid, 
"AST_vs_A" = amyloid_synuclein_tau_vs_amyloid,
"lowAS_vs_AT" = low_amyloid_synuclein_vs_amyloid_tau,
"highAS_vs_AT"= high_amyloid_synuclein_vs_amyloid_tau,
"AST_vs_AT"= amyloid_synuclein_tau_vs_amyloid_tau,
"hightAS_vs_lowAS"= high_amyloid_synuclein_vs_low_amyloid_synuclein, 
"AST_vs_lowAS"= amyloid_synuclein_tau_vs_low_amyloid_synuclein, 
"AST_vs_highAS"= amyloid_synuclein_tau_vs_high_amyloid_synuclein)
write.xlsx(list_of_datasets, file = paste0(
    "../../results/",
    tool,
    "/DEGs/", condition,".DEGs.FDRq0.05_logFC_0.25.xlsx"))
```
# GOI histogram
```{r goi_hist}
voomCounts <- readRDS(paste0("../../rObjects/", condition, ".voomCountsMatrix.rds"))
voomCounts <- as.data.frame(voomCounts)
voomCounts$gene_id  <- rownames(voomCounts)
voom_genes <- merge(voomCounts, dge.filtered.norm$genes, by = "gene_id")
goi <- subset(voom_genes, gene_name == "TTR")
goi <- as.vector(goi[2:620])
goi_melt <- melt(goi)
summary(goi_melt$value)

# histogram
ggplot(goi_melt, aes(x = value)) + 
  geom_histogram(bins = 100, fill = "gray", color = "black") + 
  labs(title = "TTR", x=NULL, y=NULL) +
  xlab("TTR log2(CPM)") + ylab("# of samples") +
  theme_bw() 

path <- paste0("../../results/", tool, "/goi/TTR.histogram")
saveToPDF(paste0(path, ".pdf"), width = 8, height = 5)
```
