---
title: "Dummy DE plots"
author: "Kimberly Olney"
date: "2/10/2023"
output: html_document
---

# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
library(ggpubr)
source(here::here("scripts/R", "file_paths_and_colours.R"))
```

# Make fake data
```{r}
# by sex
X <- c("Female (46,XX)", "Male (46,XY)")
Y <- c(1, 3)
df_sex <- rbind(Y)
colnames(df_sex) <- X
mdf_sex <- reshape2::melt(df_sex)

# simple
X <- c("Control", "Lewy Body Dementia (LBD)")
Y <- c(1.5, 3.5)
df_sim <- rbind(Y)
colnames(df_sim) <- X
df_sim <- reshape2::melt(df_sim)

# Additive
X <- c("Control", "Lewy Body Dementia (LBD)")
Y_male <- c(1, 3)
Y_female <- c(2, 4)
df_add <- rbind(Y_male, Y_female)
colnames(df_add) <- X
mdf_add <- reshape2::melt(df_add)

# Interactive
X <- c("Control", "Lewy Body Dementia (LBD)")
Y_male <- c(1, 3)
Y_female <- c(2, 6)
df_inter <- rbind(Y_male, Y_female)
colnames(df_inter) <- X
mdf_inter <- reshape2::melt(df_inter)
```
# Plot
```{r}
simple_model <- ggplot(df_sim, aes(x = Var2, y = value, group = Var1)) + 
geom_line(aes(color = Var1)) + 
geom_point(size = 3, aes(color = Var1, shape = Var1)) +
  scale_color_manual(values = c("gray20")) +
  scale_shape_manual(values = c(17)) +
  ggtitle("Simple model
~ pathology") + 
  labs(x = "pathology", y = "gene expression") +
  theme_bw() +
    theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.title.x = element_text(size = 7),
    axis.text.x = element_text(size = 7),
    axis.title.y = element_text(size = 7),
    plot.title = element_text(size = 7.5, margin = margin(0,0,1,0))) +
   scale_y_continuous(breaks = seq(0,6,by=1), limits = c(0,6.5))
simple_model
path <-paste0( "../../results/dummy_plots/simple_model")
saveToPDF(paste0(path, ".pdf"), width = 2.5, height = 2.5)

additive_model <- ggplot(mdf_add, aes(x = Var2, y = value, group = Var1)) + 
geom_line(aes(linetype = Var1, color = Var1)) + 
geom_point(size = 3, aes(color = Var1, shape = Var1)) +
  scale_color_manual(values = c("darkorange","purple")) +
  scale_shape_manual(values = c(15, 16)) +
  ggtitle("Additive model
~ pathology + sex") + 
  labs(x = "pathology", y = "gene expression") +
  theme_bw() +
    theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.title.x = element_text(size = 7),
    axis.text.x = element_text(size = 7),
    axis.title.y = element_text(size = 7),
    plot.title = element_text(size = 7.5, margin = margin(0,0,1,0))) +
   scale_y_continuous(breaks = seq(0,6,by=1), limits = c(0,6.5))
additive_model
path <-paste0( "../../results/dummy_plots/additive_model")
saveToPDF(paste0(path, ".pdf"), width = 2.5, height = 2.5)

interactive_model <- ggplot(mdf_inter, aes(x = Var2, y = value, group = Var1)) + 
geom_line(aes(linetype = Var1, color = Var1)) + 
geom_point(size = 3, aes(color = Var1, shape = Var1)) +
  scale_color_manual(values = c("darkorange","purple")) +
  scale_shape_manual(values = c(15, 16)) +
  ggtitle("Interactive model
~ pathology + sex + pathology:sex") + 
  labs(x = "pathology", y = "gene expression") +
  theme_bw() +
    theme(
    legend.position = "none",
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(), 
    axis.title.x = element_text(size = 7),
    axis.text.x = element_text(size = 7),
    axis.title.y = element_text(size = 7),
    plot.title = element_text(size = 7.5, margin = margin(0,0,1,0))) +
   scale_y_continuous(breaks = seq(0,6,by=1), limits = c(0,6.5))
interactive_model
path <-paste0( "../../results/dummy_plots/interactive_model")
saveToPDF(paste0(path, ".pdf"), width = 2.5, height = 2.5)
```