---
title: "GOI within Synapse expression data "
author: "Kimberly Olney"
date: "3/21/2023"
output: html_document
---

# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
library(RColorBrewer)
```
# Mayo CPM
```{r}
Mayo_meta <- read.csv("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/RNAseq_Harmonization_Mayo_combined_metadata.csv")
Mayo_counts <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/Mayo_Filtered_counts_(greater_than_1cpm).tsv")
ENO2 <- subset(Mayo_counts, feature == "ENSG00000111674")

# subset by gene of interest (goi)
goi_counts <- subset(Mayo_counts, feature == "ENSG00000111674")
goi_melt <- reshape2::melt(goi_counts) # reshape data 

# rename variable to specimenID to merge with metadata
names(goi_melt)[names(goi_melt) == "variable"] <- "specimenID" # rename columns to merge with metadata 
#goi_melt$specimenID <- gsub("X", "", goi_melt$specimenID)
goi_melt$specimenID <- sub('.', '', goi_melt$specimenID)
df <- merge(goi_melt, Mayo_meta, by = "specimenID")

column_variables <- c("ENSG00000111674") # gene_id to plot expression data for
df$diagnosis <- factor(df$diagnosis, levels = c("control", "pathological aging", "progressive supranuclear palsy", "Alzheimer Disease")) # make sure that the variable to compare between is a factor 
my_comparisons <- list(c("Alzheimer Disease", "control", "pathological aging", "progressive supranuclear palsy")) # define comparisons for pairwise stats
colors <- brewer.pal(n = 4, name = "Set2") # colors red to blue 

violin_plot_fun <- function(j) {
  df <- subset(df, feature == j)
  ggplot(df, aes(diagnosis, log2(value), fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle("ENO2 expression") +
    xlab("diagnosis") +
    ylab(j) +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
}
violin_plots <-
  Map(violin_plot_fun, j = column_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.Mayo.CPM.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 6.5, width = 8))

remove(df, 
       ENO2,
       goi_counts,
       goi_melt,
       Mayo_counts, 
       Mayo_meta,
       my_comparisons,
       plotnames,
       violin_plots)
```
# CQN counts
### read in counts and metadata for each study 
```{r}
Mayo_cov <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/Mayo_Covariates_ages_censored.tsv")
Mayo_counts <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/Mayo_Normalized_counts_(CQN).tsv")

MSBB_cov <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/MSBB_Covariates_ages_censored.tsv")
MSBB_counts <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/MSBB_Normalized_counts_(CQN).tsv")

ROSMAP_cov <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/ROSMAP_Covariates_ages_censored.tsv")
ROSMAP_counts <- read.delim("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/ROSMAP_Normalized_counts_(CQN).tsv")
```
# Mayo
```{r}
ENO2 <- subset(Mayo_counts, feature == "ENSG00000111674")

# subset by gene of interest (goi)
goi_counts <- subset(Mayo_counts, feature == "ENSG00000111674")
goi_melt <- reshape2::melt(goi_counts) # reshape data 

# rename variable to specimenID to merge with metadata
names(goi_melt)[names(goi_melt) == "variable"] <- "specimenID" # rename columns to merge with metadata 
#goi_melt$specimenID <- gsub("X", "", goi_melt$specimenID)
goi_melt$specimenID <- sub('.', '', goi_melt$specimenID)
df <- merge(goi_melt, Mayo_cov, by = "specimenID")
factor(df$diagnosis)

column_variables <- c("ENSG00000111674") # gene_id to plot expression data for
df$diagnosis <- factor(df$diagnosis, levels = c("CT", "PATH_AGE", "PSP", "AD")) # make sure that the variable to compare between is a factor 
colors <- brewer.pal(n = 4, name = "Set2") # colors red to blue 

violin_plot_fun <- function(j) {
  df <- subset(df, feature == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle("ENO2 expression") +
    xlab("diagnosis") +
    ylab(j) +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = column_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.Mayo.AllTissues.CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))

df$tissue <- factor(df$tissue)
tissue_variables <- c("CBE", "TCX")
violin_plot_fun <- function(j) {
  df <- subset(df, tissue == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle(paste0("ENO2 expression within ", j)) +
    xlab("diagnosis") +
    ylab("ENO2 CQN expression") +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = tissue_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.Mayo.", .y, ".CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))

remove(goi_counts,
       goi_melt,
       df,
       df_TCX,
       df_CBE,
       plotnames,
       violin_plots, 
       ENO2,
       colors,
       tissue_variables,
       column_variables)
```
# MSBB
```{r}
ENO2 <- subset(MSBB_counts, feature == "ENSG00000111674")

goi_counts <- subset(MSBB_counts, feature == "ENSG00000111674")
goi_melt <- reshape2::melt(goi_counts) # reshape data 

names(goi_melt)[names(goi_melt) == "variable"] <- "specimenID" 
df <- merge(goi_melt, MSBB_cov, by = "specimenID")
factor(df$diagnosis)
column_variables <- c("ENSG00000111674") 
df$diagnosis <- factor(df$diagnosis, levels = c("CT", "AD", "OTHER")) 
colors <- brewer.pal(n = 3, name = "Set2") # colors red to blue 

# Tissues FP IFG PHG STG 
# All
violin_plot_fun <- function(j) {
  df <- subset(df, feature == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle("ENO2 expression") +
    xlab("diagnosis") +
    ylab(j) +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = column_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.MSBB.AllTissues.CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))
df$tissue <- factor(df$tissue)
tissue_variables <- c("FP", "IFG", "PHG", "STG")
violin_plot_fun <- function(j) {
  df <- subset(df, tissue == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle(paste0("ENO2 expression within ", j)) +
    xlab("diagnosis") +
    ylab("ENO2 CQN expression") +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = tissue_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.MSBB.", .y, ".CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))

remove(goi_counts,
       goi_melt,
       df,
       plotnames,
       violin_plots, 
       ENO2,
       tissue_variables,
       colors,
       column_variables)
```
# ROSMAP
```{r}
ENO2 <- subset(ROSMAP_counts, feature == "ENSG00000111674")

goi_counts <- subset(ROSMAP_counts, feature == "ENSG00000111674")
goi_melt <- reshape2::melt(goi_counts) # reshape data 

names(goi_melt)[names(goi_melt) == "variable"] <- "specimenID" 
df <- cbind(goi_melt, ROSMAP_cov)
factor(df$diagnosis)
column_variables <- c("ENSG00000111674") 
df$diagnosis <- factor(df$diagnosis, levels = c("CT", "AD", "OTHER")) 
colors <- brewer.pal(n = 3, name = "Set2") # colors red to blue 

# All
violin_plot_fun <- function(j) {
  df <- subset(df, feature == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle("ENO2 expression") +
    xlab("diagnosis") +
    ylab(j) +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = column_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.ROSMAP.AllTissues.CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))
df$tissue <- factor(df$tissue)
tissue_variables <- c("DLPFC", "ACC", "PCC")
violin_plot_fun <- function(j) {
  df <- subset(df, tissue == j)
  ggplot(df, aes(diagnosis, value, fill = diagnosis)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA) + 
    geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    ggtitle(paste0("ENO2 expression within ", j)) +
    xlab("diagnosis") +
    ylab("ENO2 CQN expression") +
    stat_compare_means() +
    scale_fill_manual(values=colors) +
    theme(legend.position = "none")
}
violin_plots <-
  Map(violin_plot_fun, j = tissue_variables)
violin_plots

plotnames = imap(violin_plots, ~paste0("/research/labs/neurology/fryer/m239830/synapse_RNAseq_harmonization/results/goi/ENO2.ROSMAP.", .y, ".CQN.pdf")) %>%
  flatten()
plotnames
walk2(plotnames, violin_plots, ~ggsave(filename = .x, plot = .y, 
                                    height = 5.5, width = 8))
```
```{r}
```