---
title: "gprofiler2"
author: "Kimberly Olney"
date: "05/18/2023"
output: html_document
---
# gprofiler for gene enrichment analysis
A web version of gprofiler is available here: https://biit.cs.ut.ee/gprofiler/gost 
A vignette is here: https://cran.r-project.org/web/packages/gprofiler2/vignettes/gprofiler2.html#gene-identifier-conversion-with-gconvert 
```{r setup, include=FALSE, echo=FALSE}
knitr::opts_knit$set(root.dir = ".")
```

# User defined variables
```{r set_variables, warning=FALSE, echo=FALSE}
source(here::here("/research/labs/neurology/fryer/m239830/LBD_CWOW/scripts/R", "file_paths_and_colours.R"))
condition <- c("TYPE") #  TYPE
tool <- c("star")
```

# Read in DEGs
The DEGs are already ordered by smallest to largest adjusted p-value.
```{r loop, echo=FALSE, eval = FALSE}
allComparisons <- c("LBDvsControl", "LBDvsAD", "ADvsControl") # no DEGs "PAvsControl"
# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/DEGs/", condition, "_", i,
    "_gene_DEGs_FDRq0.05_logFC_0.25.txt")
  df <- assign(paste0(i),
         tryCatch(
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ), error=function(e) NULL))
  up <- subset(df$gene_name, df$logFC > 0, sort = FALSE)
  assign(paste0(i, "_up"), up)
  down <- subset(df$gene_name, df$logFC < 0, sort = FALSE)
  assign(paste0(i, "_down"), down)
  
  # gprofiler
  gp_up <- gost(up, ordered_query = TRUE, organism = "hsapiens")
  gp_down <- gost(down, ordered_query = TRUE, organism = "hsapiens")
  
  up_names = gconvert(up, organism = "hsapiens")
  down_names = gconvert(down, organism = "hsapiens")
  multi_gp = gost(list("down-regulated" = down_names, 
                     "up-regulated" = up_names), ordered_query = TRUE, 
                     organism = "hsapiens")
  # rearrange so that up-regulated is on top 
  neworder <- c("up-regulated","down-regulated")
  multi_gp$result <- arrange(transform(multi_gp$result,
             query=factor(query,levels=neworder)),query)
  print(paste("i =", i))
  # interactive plot 
  gostplot(multi_gp, interactive = TRUE)
  p_up_and_down = gostplot(multi_gp, interactive = FALSE)
  p <- publish_gostplot(p_up_and_down)
  path <- paste0("../../results/", tool, "/gprofiler/", i, "_up_and_down_gprofiler")
  pdf(paste0(path, ".pdf"), height = 6, width = 8)
  print(p)
  dev.off()
  
  # needed to convert to enrichResult object
  up_names = gconvert(up, organism = "hsapiens") 
  down_names = gconvert(down,organism = "hsapiens")
  # enrichment analysis using gene names
  multi_gp = gost(list("up-regulated" = up_names$name, "down-regulated" = down_names$name), 
                  multi_query = FALSE, evcodes = TRUE, ordered_query = TRUE, organism = "hsapiens")
  write.table(up_names, paste0("../../results/", tool,"/gprofiler/", 
                               i, "_up_gene_descriptions.txt"), 
              sep = "\t", quote = FALSE, row.names = FALSE)
  write.table(down_names, paste0("../../results/", tool,"/gprofiler/", 
                               i, "_down_gene_descriptions.txt"), 
              sep = "\t", quote = FALSE, row.names = FALSE)
  # reorder so that up-regulated is on top
  neworder <- c("up-regulated","down-regulated")
  multi_gp$result <- arrange(transform(multi_gp$result,
             query=factor(query,levels=neworder)),query)

  # modify the g:Profiler data frame
  gp_mod = multi_gp$result[,c("query", "source", "term_id", "term_name", "p_value", 
                            "query_size", "intersection_size","term_size", 
                            "effective_domain_size","intersection")] 
  # get the gene name size for each GO 
  gp_mod$GeneRatio = paste0(gp_mod$intersection_size, "/", gp_mod$query_size)
  gp_mod$BgRatio = paste0(gp_mod$term_size, "/", gp_mod$effective_domain_size) 
  names(gp_mod) = c("Cluster", "Category", "ID", "Description", "p.adjust", 
                    "query_size", "Count", "term_size", "effective_domain_size",
                    "gene_name", "GeneRatio", "BgRatio") 
  gp_mod$gene_name = gsub(",", "/", gp_mod$gene_name)
  row.names(gp_mod) = make.names(gp_mod$ID, unique = TRUE)
  # define as compareClusterResult object
  gp_mod_cluster = new("compareClusterResult", compareClusterResult = gp_mod)
  # define as enrichResult object
  gp_mod_enrich = new("enrichResult", result = gp_mod)
  bar <- barplot(gp_mod_enrich, showCategory = 15, font.size = 8) + 
  ggplot2::facet_grid(~Cluster) +
  ggplot2::ylab("Intersection size")
  path <- paste0("../../results/", tool, "/gprofiler/", i, "_up_and_down_gprofiler_bar-plot")
  pdf(paste0(path, ".pdf"), height = 6, width = 4.5)
  print(bar)
  dev.off()
  
  # output table 
  write.table(gp_mod_enrich@result, paste0("../../results/", tool,
                                           "/gprofiler/", i, "_up_and_down_gp_mod_enrich.txt"), 
              sep = "\t", quote = FALSE, row.names = FALSE)
}
```
# Make excel table
```{r excel, echo=FALSE, eval=FALSE}
# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/gprofiler/", i,
    "_up_and_down_gp_mod_enrich.txt"
  )
  assign(paste0(i),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
}
allComparisons
list_of_datasets <- list(
"ADvsControl" = ADvsControl,     
"LBDvsControl" = LBDvsControl,
"LBDvsAD "= LBDvsAD)
write.xlsx(list_of_datasets, file = paste0(
    "../../results/",
    tool,
    "/gprofiler/", condition,"_up_and_down_gp_mod_enrich.xlsx"))
```
# Excel gene name descriptions
```{r gene_name, eval = FALSE}
# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/gprofiler/", i,
    "_up_gene_descriptions.txt"
  )
  assign(paste0(i),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
}
list_of_datasets <- list(
"ADvsControl" = ADvsControl,     
"LBDvsControl" = LBDvsControl,
"LBDvsAD "= LBDvsAD)
write.xlsx(list_of_datasets, file = paste0(
    "../../results/",
    tool,
    "/gprofiler/", condition,"_up_gene_descriptions.xlsx"))

# first read in the files
for (i in allComparisons) {
  filepath <- paste0("../../results/",tool,
    "/gprofiler/", i,
    "_down_gene_descriptions.txt"
  )
  assign(paste0(i),
         read.delim(
           filepath,
           header = TRUE,
           sep = "\t",
           stringsAsFactors = FALSE
         ))
}
write.xlsx(list_of_datasets, file = paste0(
    "../../results/",
    tool,
    "/gprofiler/", condition,"_down_gene_descriptions.xlsx"))
```
# function
```{r function}
publish_gostplot_intersect <- function (p, highlight_terms = NULL, filename = NULL, width = NA, 
          height = NA) 
{
  if (!("ggplot" %in% class(p))) {
    warning("Highlighting terms in a Manhattan plot is available for a ggplot object only.\nPlease set 'interactive = F' in the gostplot() function and try again.")
    return(NULL)
  }
  term_id <- logpval <- term_size_scaled <- id <- query <- p_value <- NULL
  if (!is.null(highlight_terms)) {
    if (is.data.frame(highlight_terms)) {
      message("The input 'highlight_terms' is a data.frame and therefore the column 'term_id' will be used for detection.")
      if ("term_id" %in% colnames(highlight_terms)) {
        highlight_terms <- highlight_terms$term_id
      }
      else {
        stop("No column named 'term_id'.")
      }
    }
    df <- p$data
    subdf <- base::subset(df, term_id %in% highlight_terms)
    if (nrow(subdf) == 0) {
      message("None of the term IDs in the 'highlight_terms' was found from the results.")
      return(p)
    }
    highlight_terms <- unique(highlight_terms)
    subdf$id <- match(subdf$term_id, highlight_terms)
    p <- p + ggplot2::geom_point(data = subdf, ggplot2::aes(x = order, 
                                                            y = logpval, size = term_size_scaled), pch = 21, 
                                 colour = "black")
    p <- p + ggplot2::geom_text(data = subdf, size = 4, colour = "white", 
                                ggplot2::aes(label = as.character(id), family = "mono", 
                                             fontface = "bold"), hjust = -1.2, vjust = -0.05) + 
      ggplot2::geom_text(data = subdf, size = 4, colour = "black", 
                         fontface = "bold", ggplot2::aes(label = as.character(id)), 
                         hjust = -1.2, vjust = -0.05)
    pseudo_gostres <- list(result = data.frame(subdf), meta = list(query_metadata = list(queries = sapply(unique(subdf$query), 
                                                                                                          function(x) NULL))))
    tb <- publish_gosttable(pseudo_gostres, highlight_terms = highlight_terms, 
                            use_colors = TRUE, show_columns = c("source", "term_name", 
                                                                "intersection_size"), filename = NULL, ggplot = FALSE)
    h <- grid::unit.c(grid::unit(1, "null"), sum(tb$heights) + 
                        grid::unit(3, "mm"))
    w <- grid::unit.c(grid::unit(1, "null"))
    tg <- gridExtra::grid.arrange(p, tb, ncol = 1, heights = h, 
                                  widths = w, newpage = TRUE)
    p <- ggplot2::ggplot() + ggplot2::annotation_custom(tg) + 
      ggplot2::geom_blank() + ggplot2::theme_void()
  }
  if (is.null(filename)) {
    return(p)
  }
  else {
    imgtype <- strsplit(basename(filename), split = "\\.")[[1]][-1]
    if (length(imgtype) == 0) {
      filename = paste0(filename, ".pdf")
    }
    if (tolower(imgtype) %in% c("png", "pdf", "jpeg", "tiff", 
                                "bmp")) {
      if (is.na(width)) {
        width = max(grDevices::dev.size()[1], 8)
      }
      if (is.na(height)) {
        height = max(grDevices::dev.size()[2], 6)
      }
      ggplot2::ggsave(filename = filename, plot = p, width = width, 
                      height = height, limitsize = F)
      message("The image is saved to ", filename)
      return(p)
    }
    else {
      stop("The given file format is not supported.\nPlease use one of the following extensions: .png, .pdf, .jpeg, .tiff, .bmp")
    }
  }
}
```
# LBD vs Control
```{r}
i <- "LBDvsControl"
filepath <- paste0(
  "../../results/",
  tool,
  "/DEGs/",
  condition,
  "_",
  i,
  "_gene_DEGs_FDRq0.05_logFC_0.25.txt"
)
df <- assign(paste0(i),
             tryCatch(
               read.delim(
                 filepath,
                 header = TRUE,
                 sep = "\t",
                 stringsAsFactors = FALSE
               ),
               error = function(e)
                 NULL
             ))
up <- subset(df$gene_name, df$logFC > 0, sort = FALSE)
assign(paste0(i, "_up"), up)
down <- subset(df$gene_name, df$logFC < 0, sort = FALSE)
assign(paste0(i, "_down"), down)

# gprofiler
gp_up <- gost(up, ordered_query = TRUE, organism = "hsapiens")
gp_down <- gost(down, ordered_query = TRUE, organism = "hsapiens")

#--- up
# interactive plot
gostplot(gp_up, interactive = TRUE)
p_up = gostplot(gp_up, interactive = FALSE)
plot_up <- publish_gostplot_intersect(p_up, highlight_terms = c("GO:0005515", "GO:0031982", "GO:0071944", "GO:0023052","GO:0051716",  "WP:WP3945"))
plot_up
path <- paste0("../../results/", tool, "/gprofiler/", i, "_up_gprofiler")
pdf(paste0(path, ".pdf"), height = 6, width = 8)
print(plot_up)
dev.off()

#--- down
# interactive plot
gostplot(gp_down, interactive = TRUE)
p_down = gostplot(gp_down, interactive = FALSE)
plot_down <- publish_gostplot_intersect(p_down, highlight_terms = c("GO:0016491", "GO:0005759", "GO:0016054", "KEGG:01212", "WP:WP5241"))
plot_down
path <- paste0("../../results/", tool, "/gprofiler/", i, "_down_gprofiler")
pdf(paste0(path, ".pdf"), height = 6, width = 8)
print(plot_down)
dev.off()
```
```{r}
row1 <-
  ggarrange(
    NULL,
    NULL,
    NULL,
    NULL,
    ncol = 4,
    labels = c("up-regulated", "", "", ""),
    font.label = list(size = 9, color = "red")
  )

row3 <-
  ggarrange(
    NULL,
    NULL,
    NULL,
    NULL,
    ncol = 4,
    labels = c("down-regulated", "", "", ""),
    font.label = list(size = 9, color = "blue")
  )
combind <-
  ggarrange(
    row1,
    plot_up,
    row3,
    plot_down,
    nrow = 4,
    labels = c("a)", "", "b)", ""),
    heights = c(0.1, 1, 0.05, 1),
    font.label = list(size = 8)
  )
combind

path <- paste0("../../results/manuscript_figures/Supplemental_Figure_LBD_vs_Control_gProfiler_bubble")
saveToPDF(paste0(path, ".pdf"), width = 8.5, height = 11)
```


# GO Plot
```{r plot, eval=FALSE, echo=FALSE, eval = FALSE}
up <- subset(gp_mod, Cluster == "up-regulated")
#up <- up[1:15, ]
p_enrich <- ggplot(data=up, aes(x=Count, y=Description)) +
   geom_bar(stat="identity", aes(fill = p.adjust), width = .65) +
  theme(axis.title.x = element_text(size = 12),
        axis.text.x = element_text(size = 10)) +
  theme(axis.title.y = element_text(size = 12),
        axis.text.y = element_text(size = 10)) +
    theme_bw() +  # set color theme
  #  scale_y_discrete(expand=c(0,0)) +
  scale_fill_gradientn(colours = c("darkmagenta", "mediumorchid3", "grey"), values = rescale(c(0,.01, 0.05)), guide = "legend", limits=c(0,0.05)) + labs(x = "Gene count", y = "")
p_enrich
```




