---
title: "Gene violins"
author: "Kimberly Olney"
date: "2023-07-28"
output: html_document
---

# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```
# User defined variables
```{r set_variables}
source(here::here("scripts/R", "file_paths_and_colours.R"))
library("readxl")
#source(here::here("scripts/R", "gtf_path.R"))
condition <- c("TYPE")
tool <- "star"
dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))
```

#---------------------------------
# Gene violins 
```{r eval = FALSE}
dge.filtered.norm <- readRDS(paste0("../../../rObjects/dge.filtered.norm.rds"))
voomCountsMatrix <- readRDS("/research/labs/neurology/fryer/m239830/LBD_CWOW/rObjects/TYPE.voomCountsMatrix.rds")
# get the gene id that corresponds to the gene name 
genes <- dge.filtered.norm$genes # gene information 
goi <- subset(genes, gene_name == "SERPINA5" | gene_name == "MAG" | gene_name == "LGR6" | gene_name == "HBB") # gene of interest 

# subset counts 
goi_counts <- subset(voomCountsMatrix, rownames(voomCountsMatrix) %in% rownames(goi))
goi_melt <- reshape2::melt(goi_counts) # reshape data 
names(goi_melt)[names(goi_melt) == "Var2"] <- "NPID" # rename columns to merge with metadata 
names(goi_melt)[names(goi_melt) == "Var1"] <- "gene_id"
df <- merge(goi_melt, metadata, by = "NPID")

colors <- c("#4682B4", "thistle3", "thistle4")
df$LBD.type <- factor(df$LBD.type, levels =c("no LBs", "TLBD", "DLBD", "BLBD"))
df <- subset(df, LBD.type != "BLBD")
df <- subset(df, TYPE != "AD")
df <- subset(df, TYPE != "PA")

df$LBD.type <-gsub("no LBs","Control",df$LBD.type)
df$LBD.type <- factor(df$LBD.type, levels =c("Control", "TLBD", "DLBD"))
```
### MAG
```{r MAG}
exp_data <- subset(df, gene_id == "ENSG00000105695.15")
MAG_exp_plot <- ggplot(exp_data, aes(LBD.type, value, fill = LBD.type)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA, color = "black") + 
   # geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
    labs(
        title = "MAG expression",
        x = "",
        y = expression(log[2] ~ "(CPM)")
      )  +
    scale_fill_manual(values=alpha(c(colors),0.5)) #  scale_fill_manual(values = alpha(c("blue", "red"), 0.2))
MAG_exp_plot
```
### HBB
```{r HBB}
exp_data <- subset(df, gene_id == "ENSG00000244734.4")
HBB_exp_plot <- ggplot(exp_data, aes(LBD.type, value, fill = LBD.type)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA, color = "black") + 
   # geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
    labs(
        title = "HBB expression",
        x = "",
        y = expression(log[2] ~ "(CPM)")
      )  +
    scale_fill_manual(values=alpha(c(colors),0.5)) #  scale_fill_manual(values = alpha(c("blue", "red"), 0.2))
HBB_exp_plot
```
### LGR6
```{r LGR6}
exp_data <- subset(df, gene_id == "ENSG00000133067.18")
LGR6_exp_plot <- ggplot(exp_data, aes(LBD.type, value, fill = LBD.type)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA, color = "black") + 
   # geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
    labs(
        title = "LGR6 expression",
        x = "",
        y = expression(log[2] ~ "(CPM)")
      )  +
    scale_fill_manual(values=alpha(c(colors),0.5)) #  scale_fill_manual(values = alpha(c("blue", "red"), 0.2))
LGR6_exp_plot
```
### SERPINA5
```{r SERPINA5}
exp_data <- subset(df, gene_id == "ENSG00000188488.14")
SERPINA5_exp_plot <- ggplot(exp_data, aes(LBD.type, value, fill = LBD.type)) +
    geom_violin() +
    geom_boxplot(width = 0.1, outlier.shape=NA, color = "black") + 
   # geom_jitter(shape=16, position=position_jitter(0.2), alpha = 0.1) +
    theme_bw() +
    theme(legend.position = "none", 
          plot.margin = margin(0.1, 0.2, 0.5, 0.3, "cm"), #t,r,b,l
             axis.title.x = element_text(size = 8),
             axis.text.x = element_text(size = 8),
             axis.title.y = element_text(size = 8),
             axis.text.y = element_text(size = 8),
             plot.title = element_text(size = 8, margin = margin(0,0,0.3,0))) +
    labs(
        title = "SERPINA5 expression",
        x = "",
        y = expression(log[2] ~ "(CPM)")
      )  +
    scale_fill_manual(values=alpha(c(colors),0.5)) #  scale_fill_manual(values = alpha(c("blue", "red"), 0.2))
SERPINA5_exp_plot

```
