---
title: "Ecoli Pigs Single Cell Brain Re-cluster"
author: "Kimberly Olney"
date: "06/09/2023"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

# Set working directory
```{r working_directory}
knitr::opts_knit$set(root.dir = ".")
```
# Libraris, paths, colors
```{r}
source(here::here("snRNA/scripts/R", "file_paths_and_colours.R"))
```
# Read in object
```{r read_object, echo=FALSE, eval=TRUE}
# read object
pigs.annotated <- readRDS("../../rObjects/brain_annotated.rds")
table(pigs.annotated$annotated_clusters)
```
## Subset
```{r}
Astrocytes <- subset(pigs.annotated, annotated_clusters == "Astrocytes")
Fibroblast <- subset(pigs.annotated, annotated_clusters == "Fibroblast-like")
Microglia <- subset(pigs.annotated, annotated_clusters == "Microglia Macrophage")
Oligodendrocytes <- subset(pigs.annotated, annotated_clusters == "Oligodendrocytes")
Polydendrocyte <- subset(pigs.annotated, annotated_clusters == "Polydendrocyte")
# Merge more than two Seurat objects
pigs.glia <- merge(x = Astrocytes, y = list(Fibroblast, Microglia, Oligodendrocytes, Polydendrocyte))
table(pigs.glia$annotated_clusters)

Neurons <- subset(pigs.annotated, annotated_clusters == "Neurons")
Interneurons <- subset(pigs.annotated, annotated_clusters == "Interneurons")
pigs.neuron<- merge(x = Neurons, y = Interneurons)
table(pigs.neuron$annotated_clusters)
```
# re-process subsets
### Glia
```{r}
Idents(pigs.glia) <- "annotated_clusters"
# normalize if SCTtransform was used
DefaultAssay(pigs.glia) <- "RNA"
# natural-log
pigs.glia <- NormalizeData(pigs.glia, verbose = FALSE)
pigs.glia <- FindVariableFeatures(pigs.glia, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pigs.glia), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pigs.glia)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot2

all.genes <- rownames(pigs.glia)
pigs.glia <- ScaleData(pigs.glia, features = all.genes)

pigs.glia <- RunPCA(pigs.glia, features = VariableFeatures(object = pigs.glia))
# Examine and visualize PCA results a few different ways
print(pigs.glia[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(pigs.glia, dims = 1:2, reduction = "pca")
DimPlot(pigs.glia, reduction = "pca")
DimHeatmap(pigs.glia, dims = 1, cells = 500, balanced = TRUE)
DimHeatmap(pigs.glia, dims = 1:3, cells = 500, balanced = TRUE)
```
# Significant PCs
```{r}
stdv <- pigs.glia[["pca"]]@stdev
sum.stdv <- sum(pigs.glia[["pca"]]@stdev)
percent.stdv <- (stdv / sum.stdv) * 100
cumulative <- cumsum(percent.stdv)
co1 <- which(cumulative > 90 & percent.stdv < 5)[1]
co2 <- sort(which(
  (percent.stdv[1:length(percent.stdv) - 1] - 
     percent.stdv[2:length(percent.stdv)]) > 0.1), 
  decreasing = T)[1] + 1
min.pc <- min(co1, co2)
min.pc

# Determine the K-nearest neighbor graph
pigs.glia <- FindNeighbors(object = pigs.glia, dims = 1:min.pc)
pigs.glia <- FindClusters(object = pigs.glia, algorithm = 1, resolution = seq(0.1,0.8,by=0.1))
pigs.glia <- RunUMAP(pigs.glia, dims = 1:min.pc)
```
# UMAP plot
```{r}
dittoDimPlot(object = pigs.glia,
             var = "annotated_clusters",
             reduction.use = "umap",
             do.label = TRUE,
             labels.highlight = TRUE)

# explore resolutions 
DimPlot(pigs.glia,
        group.by = "RNA_snn_res.0.2",
        label = TRUE)

DimPlot(pigs.glia,
        group.by = "RNA_snn_res.0.4",
        label = TRUE)

DimPlot(pigs.glia,
        group.by = "RNA_snn_res.0.6",
        label = TRUE)

DimPlot(pigs.glia,
        group.by = "RNA_snn_res.0.8",
        label = TRUE)
```
# Save
```{r}
DefaultAssay(pigs.glia) <- "RNA"
pigs.glia$seurat_clusters <- pigs.glia$RNA_snn_res.0.8
saveRDS(pigs.glia, file = "../../rObjects/pigs.glia.unannotated.rds")
pigs.glia <- readRDS("../../rObjects/pigs.glia.unannotated.rds")
```

```{r tree}
pigs.glia <- BuildClusterTree(object = pigs.glia,
                                     dims = 1:15,
                                     reorder = FALSE,
                                     reorder.numeric = FALSE)

tree <- pigs.glia@tools$BuildClusterTree
tree$tip.label <- paste0("Cluster ", tree$tip.label)

tree_1 <- ggtree::ggtree(tree, aes(x, y)) +
  scale_y_reverse() +
  ggtree::geom_tree() +
  ggtree::theme_tree() +
  ggtree::geom_tiplab(offset = 1) +
  ggtree::geom_tippoint(color = colors[1:length(tree$tip.label)], 
                        shape = 16, size = 5) +
  coord_cartesian(clip = 'off') +
  theme(plot.margin = unit(c(0,2.5,0,0), 'cm'))
tree_1
```
# Marker exploration
## Find all markers
```{r find_all_markers}
# Find markers for each cluster
# Default is logfc.threshold = 0.25 and min.pct = 0.1
Idents(pigs.glia) <- "seurat_clusters"
all.markers <- FindAllMarkers(object = pigs.glia,
                              assay = "RNA",
                              test.use = "MAST",
                              only.pos = TRUE,
                              verbose = TRUE)

# add column
all.markers$delta_pct <- abs(all.markers$pct.1 - all.markers$pct.2)

# rename columns and rows
rownames(all.markers) <- 1:nrow(all.markers)
all.markers <- all.markers[,c(6,7,1,5,2:4,8)]
colnames(all.markers)[c(6,7)] <- c("pct_1","pct_2")

# save
saveRDS(all.markers, "../../rObjects/pigs.glia.unannotated_all_markers.rds")
```

## Top variable genes
```{r top_variable}
# print top variable genes
top20 <- pigs.glia@assays$RNA@var.features[1:20]
top20
```
```{r top_markers}
# read object
all.markers <- readRDS("../../rObjects/pigs.glia.unannotated_all_markers.rds")

# more stringent filtering
all.markers <- all.markers[all.markers$p_val_adj < 0.05,]
markers.strict <- all.markers[
  all.markers$delta_pct > summary(all.markers$delta_pct)[5],]

# compare 
table(all.markers$cluster)
table(markers.strict$cluster)

# subset
cluster0 <- markers.strict[markers.strict$cluster == 0,]
cluster1 <- markers.strict[markers.strict$cluster == 1,]
cluster2 <- markers.strict[markers.strict$cluster == 2,]
cluster3 <- markers.strict[markers.strict$cluster == 3,]
cluster4 <- markers.strict[markers.strict$cluster == 4,]
cluster5 <- markers.strict[markers.strict$cluster == 5,]
cluster6 <- markers.strict[markers.strict$cluster == 6,]
cluster7 <- markers.strict[markers.strict$cluster == 7,]
cluster8 <- markers.strict[markers.strict$cluster == 8,]
cluster9 <- markers.strict[markers.strict$cluster == 9,]
cluster10 <- markers.strict[markers.strict$cluster == 10,]
```

# Cluster Annotation
## Cluster 0 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,2)]

# UMAP with only cluster 0
DimPlot(object = subset(pigs.glia, seurat_clusters == "0"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#E69F00")

VlnPlot(pigs.glia,
        features = cluster0$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 1 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,3)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "1"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#56B4E9")

VlnPlot(pigs.glia,
        features = cluster1$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 2 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,4)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "2"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#009E73")

VlnPlot(pigs.glia,
        features = cluster2$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 3 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,4)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "3"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#F0E442")

VlnPlot(pigs.glia,
        features = cluster3$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 4 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,5)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "4"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#0072B2")

VlnPlot(pigs.glia,
        features = cluster4$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 5 -
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,6)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "5"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#D55E00")

VlnPlot(pigs.glia,
        features = cluster5$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 6 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,7)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "6"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#CC79A7")

VlnPlot(pigs.glia,
        features = cluster6$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 7 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,8)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "7"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#666666")

VlnPlot(pigs.glia,
        features = cluster7$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 8 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,9)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "8"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#AD7700")

VlnPlot(pigs.glia,
        features = cluster8$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 9 - 
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,10)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "9"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#1C91D4")

VlnPlot(pigs.glia,
        features = cluster9$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```
## Cluster 10 -
```{r,warning=FALSE,message=FALSE}
# Number of cells per condition
n_cells[,c(1,11)]
DimPlot(object = subset(pigs.glia, seurat_clusters == "10"),
        reduction = "umap", 
        label = TRUE,
        label.box = TRUE,
        label.size = 3,
        repel = TRUE,
        cols = "#007756")

VlnPlot(pigs.glia,
        features = cluster10$gene[1:10],
        cols = colors,
        stack = TRUE,
        flip = TRUE,
        split.by = "seurat_clusters")
```

